using System.Security.Cryptography;
using System.Text;
using Microsoft.Extensions.Logging;
using Npgsql;

namespace Zumbo.Persistence.PostgreSql;

public sealed partial class PostgreSqlMigrationRunner{

    public Task<string> GenerateScriptAsync(
        long? fromVersion = null,
        long? toVersion = null,
        bool idempotent = false,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        var migrations = BuildMigrations();
        var firstExcluded = fromVersion ?? 0;
        var lastIncluded = toVersion ?? migrations[^1].Version;
        if (firstExcluded < 0 || lastIncluded < 0 || firstExcluded > lastIncluded)
        {
            throw new ArgumentOutOfRangeException(nameof(fromVersion), "Migration version range is invalid.");
        }

        if (lastIncluded > migrations[^1].Version)
        {
            throw new ArgumentOutOfRangeException(nameof(toVersion), "Target migration version does not exist.");
        }

        var selected = migrations
            .Where(migration => migration.Version > firstExcluded && migration.Version <= lastIncluded)
            .ToList();
        var script = new StringBuilder();
        script.AppendLine("-- Generated by Zumbo.DatabaseMigrator. Review before production use.");
        script.AppendLine("BEGIN;");
        script.AppendLine("CREATE TABLE IF NOT EXISTS public.zumbo_schema_migrations (");
        script.AppendLine("    version bigint PRIMARY KEY,");
        script.AppendLine("    name text NOT NULL,");
        script.AppendLine("    checksum text NOT NULL,");
        script.AppendLine("    applied_at timestamptz NOT NULL DEFAULT transaction_timestamp()");
        script.AppendLine(");");
        script.AppendLine($"SELECT pg_advisory_xact_lock(hashtext('{LockName}'));\n");

        foreach (var migration in selected)
        {
            script.AppendLine($"-- Migration {migration.Version}: {migration.Name}");
            script.AppendLine(migration.UpSql.Trim());
            script.Append("INSERT INTO public.zumbo_schema_migrations (version, name, checksum) VALUES (")
                .Append(migration.Version)
                .Append(", '").Append(SqlLiteral(migration.Name))
                .Append("', '").Append(SqlLiteral(migration.Checksum)).Append("')");
            script.AppendLine(idempotent
                ? " ON CONFLICT (version) DO NOTHING;"
                : ";");
            if (idempotent)
            {
                script.Append("DO $zumbo$ BEGIN IF NOT EXISTS (SELECT 1 FROM public.zumbo_schema_migrations WHERE version = ")
                    .Append(migration.Version)
                    .Append(" AND name = '").Append(SqlLiteral(migration.Name))
                    .Append("' AND checksum = '").Append(SqlLiteral(migration.Checksum))
                    .AppendLine("') THEN RAISE EXCEPTION 'Migration ledger checksum mismatch'; END IF; END $zumbo$;");
            }
            script.AppendLine();
        }

        script.AppendLine("COMMIT;");
        return Task.FromResult(script.ToString());
    }
}
