export interface CapacityPage { readonly items:readonly CapacityPlan[]; readonly totalCount:number; }
export interface CapacityPlan { readonly id:string; readonly name:string; readonly description?:string|null; readonly periodStart:string; readonly periodEnd:string; readonly portfolioId?:string|null; readonly projectIds:readonly string[]; readonly members:readonly CapacityMember[]; readonly allocations:readonly CapacityAllocation[]; readonly viewerUserIds:readonly string[]; readonly canEdit:boolean; readonly archived:boolean; readonly version:number; }
export interface CapacityMember { readonly userId:string; readonly teamId?:string|null; readonly weeklyCapacityHours:number; }
export interface CapacityAllocation { readonly id?:string|null; readonly userId:string; readonly projectId:string; readonly startDate:string; readonly endDate:string; percent:number; }
export interface CapacitySummary { readonly people:number; readonly capacityHours:number; readonly allocatedHours:number; readonly remainingHours:number; readonly overCapacityPeople:number; readonly openItems:number; readonly estimatedPoints:number; readonly unestimatedItems:number; readonly unscheduledItems:number; }
export interface CapacityMemberSnapshot { readonly userId:string; readonly weeklyCapacityHours:number; readonly capacityHours:number; readonly allocatedHours:number; readonly remainingHours:number; readonly allocationPercent:number; readonly state:string; readonly openItems:number; readonly estimatedPoints:number; }
export interface CapacityProjectSnapshot { readonly projectId:string; readonly key:string; readonly name:string; readonly allocatedPeople:number; readonly allocatedHours:number; readonly openItems:number; readonly estimatedPoints:number; readonly unestimatedItems:number; }
export interface CapacitySnapshot { readonly sourceStatus:string; readonly truncated:boolean; readonly unavailableProjectIds:readonly string[]; readonly summary:CapacitySummary; readonly members:readonly CapacityMemberSnapshot[]; readonly projects:readonly CapacityProjectSnapshot[]; }
export interface CapacityContext { readonly plan:CapacityPlan; readonly snapshot:CapacitySnapshot; }
export interface CapacityUser { readonly id:string; readonly username?:string|null; readonly email?:string|null; }
export interface CapacityScenario { readonly baseline:CapacitySnapshot; readonly candidate:CapacitySnapshot; }
export interface CapacityDraft { id?:string; name:string; description:string; periodStart:string; periodEnd:string; projectId:string; weeklyCapacityHours:number; version?:number; }
