import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {IonBackButton,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonTitle,IonToolbar} from '@ionic/angular/standalone';
import {finalize,forkJoin} from 'rxjs';
import {normalizeApiError,ZumboSessionService} from '@zumbo/modern-shared';
import {MobileConnectivityService} from '../../shell/mobile-connectivity.service';
import {MobileWorkspaceStore} from '../../shell/mobile-workspace.store';
import {GoalContext,GoalDraft,GoalPortfolio,GoalUser,KeyResult,KeyResultDraft} from './mobile-goal.models';
import {MobileGoalService} from './mobile-goal.service';
@Component({selector:'zumbo-mobile-goals',imports:[FormsModule,IonBackButton,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonTitle,IonToolbar],providers:[MobileGoalService],templateUrl:'./mobile-goal.page.html',styleUrls:['./mobile-strategy.page.scss','./mobile-strategy-detail.scss','./mobile-strategy-edit.scss']})
export class MobileGoalPage{
 private readonly api=inject(MobileGoalService);private readonly session=inject(ZumboSessionService);protected readonly store=inject(MobileWorkspaceStore);protected readonly connectivity=inject(MobileConnectivityService);protected readonly items=signal<readonly GoalContext['goal'][]>([]);protected readonly users=signal<readonly GoalUser[]>([]);protected readonly portfolios=signal<readonly GoalPortfolio[]>([]);protected readonly context=signal<GoalContext|null>(null);protected readonly selectedId=computed(()=>this.context()?.goal.id||'');protected readonly loading=signal(true);protected readonly busy=signal(false);protected readonly error=signal<string|null>(null);protected readonly editor=signal<'none'|'goal'|'result'>('none');protected selectedResult='';protected progressDraft={currentValue:0,confidence:80,note:''};protected statusDraft={status:'Active',health:'OnTrack',confidence:80,note:''};protected goalDraft:GoalDraft=this.newGoalDraft();protected resultDraft:KeyResultDraft=this.newResultDraft();
 constructor(){this.load();}
 protected load(done?:()=>void,preferredId?:string){this.loading.set(true);this.error.set(null);forkJoin({page:this.api.list(),catalog:this.api.catalog()}).pipe(finalize(()=>{this.loading.set(false);done?.();})).subscribe({next:value=>{this.items.set(value.page.items.filter(item=>!item.archived));this.users.set(value.catalog.users);this.portfolios.set(value.catalog.portfolios.items);const id=preferredId||this.selectedId()||this.items()[0]?.id;if(id)this.select(id);},error:()=>this.error.set('Hedefler yüklenemedi.')});}
 protected select(id:string){this.api.detail(id).subscribe({next:value=>{this.context.set(value);this.editor.set('none');this.goalDraft=this.newGoalDraft(value.goal);this.statusDraft={status:value.goal.status,health:value.goal.health,confidence:value.goal.confidence??80,note:''};},error:()=>this.error.set('Hedef ayrıntısı yüklenemedi.')});}
 protected refresh(event:Event){this.load(()=>void(event.target as unknown as{complete():Promise<void>}).complete());}
 protected result(){return this.context()?.goal.keyResults.find(item=>item.id===this.selectedResult);}
 protected choose(item:KeyResult){this.selectedResult=item.id;this.progressDraft.currentValue=item.currentValue;this.progressDraft.confidence=item.confidence??80;this.progressDraft.note='';}
 protected saveProgress(){const context=this.context(),result=this.result();if(!context||!result?.canUpdate||!this.progressDraft.note.trim()||this.busy()||this.connectivity.offline())return;this.busy.set(true);this.api.progress(context.goal,result.id,{...this.progressDraft,note:this.progressDraft.note.trim()}).pipe(finalize(()=>this.busy.set(false))).subscribe({next:goal=>{this.context.set({...context,goal});this.selectedResult='';},error:value=>this.error.set(normalizeApiError(value).message||'İlerleme kaydedilemedi.')});}
 protected saveStatus(){const context=this.context();if(!context?.goal.canUpdateStatus||!this.statusDraft.note.trim())return;this.mutate(this.api.updateStatus(context.goal,{...this.statusDraft,note:this.statusDraft.note.trim()}),value=>{this.context.set({...context,goal:value});this.statusDraft.note='';});}
 protected statusLabel(value:string){return ({Draft:'Taslak',Active:'Aktif',AtRisk:'Riskli',Completed:'Tamamlandı',Cancelled:'İptal edildi'} as Record<string,string>)[value]||value;}
 protected healthLabel(value:string){return ({Green:'İyi',Yellow:'Dikkat',Red:'Kritik',NoUpdate:'Güncelleme yok',OnTrack:'Yolunda',AtRisk:'Riskli',OffTrack:'Kritik'} as Record<string,string>)[value]||value;}
 protected sourceLabel(value:string){return ({Ready:'Hazır',Available:'Hazır',Partial:'Kısmi',Unavailable:'Kullanılamıyor'} as Record<string,string>)[value]||value;}
 protected userName(id:string){const user=this.users().find(item=>item.id===id);return user?.username||user?.email||'Kullanıcı';}
 protected createGoal(){this.context.set(null);this.goalDraft=this.newGoalDraft();this.editor.set('goal');}
 protected editGoal(){const goal=this.context()?.goal;if(!goal?.canEdit)return;this.goalDraft=this.newGoalDraft(goal);this.editor.set('goal');}
 protected saveGoal(){const draft=this.goalDraft;if(!draft.name.trim()||!draft.periodStart||!draft.periodEnd||draft.periodEnd<draft.periodStart)return;this.mutate(this.api.saveGoal(draft),value=>{this.context.set(null);this.load(undefined,value.id);});}
 protected archive(){const goal=this.context()?.goal;if(!goal?.canEdit||!confirm('Bu hedefi arşivlemek istiyor musunuz?'))return;this.mutate(this.api.archive(goal),()=>{this.context.set(null);this.load();});}
 protected editResult(item?:KeyResult){const goal=this.context()?.goal;if(!goal?.canEdit)return;this.resultDraft=this.newResultDraft(item);this.editor.set('result');}
 protected saveResult(){const goal=this.context()?.goal,draft=this.resultDraft;if(!goal?.canEdit||!draft.name.trim()||!draft.ownerUserId||!draft.unit.trim()||draft.baselineValue===draft.targetValue)return;this.mutate(this.api.saveKeyResult(goal,draft),value=>this.select(value.id));}
 protected toggleGoalProject(id:string,on:boolean){this.goalDraft.projectIds=on?[...new Set([...this.goalDraft.projectIds,id])]:this.goalDraft.projectIds.filter(value=>value!==id);}
 protected toggleInitiative(key:string,on:boolean){this.goalDraft.initiativeKeys=on?[...new Set([...this.goalDraft.initiativeKeys,key])]:this.goalDraft.initiativeKeys.filter(value=>value!==key);}
 protected initiativeOptions(){return this.portfolios().flatMap(portfolio=>portfolio.initiatives.map(item=>({key:`${portfolio.id}:${item.id}`,label:`${portfolio.name} · ${item.name}`})));}
 protected cancelEditor(){if(this.context())this.editor.set('none');else this.load();}
 private mutate<T>(request:import('rxjs').Observable<T>,done:(value:T)=>void){if(this.busy()||this.connectivity.offline())return;this.busy.set(true);this.error.set(null);request.pipe(finalize(()=>this.busy.set(false))).subscribe({next:done,error:value=>this.error.set(normalizeApiError(value).message||'İşlem tamamlanamadı.')});}
 private newGoalDraft(item?:GoalContext['goal']):GoalDraft{const now=new Date(),quarter=Math.floor(now.getMonth()/3)*3,start=new Date(now.getFullYear(),quarter,1),end=new Date(now.getFullYear(),quarter+3,0),key=(value:Date)=>value.toISOString().slice(0,10);return{id:item?.id,name:item?.name||'',description:item?.description||'',periodStart:item?.periodStart||key(start),periodEnd:item?.periodEnd||key(end),viewerUserIds:[...(item?.viewerUserIds||[])],initiativeKeys:(item?.initiativeLinks||[]).map(link=>`${link.portfolioId}:${link.initiativeId}`),projectIds:[...(item?.projectIds||[])],version:item?.version};}
 private newResultDraft(item?:KeyResult):KeyResultDraft{return{id:item?.id,name:item?.name||'',description:item?.description||'',ownerUserId:item?.ownerUserId||this.session.currentUser()?.id||'',baselineValue:item?.baselineValue??0,targetValue:item?.targetValue??100,initialValue:item?.currentValue??0,unit:item?.unit||'%',direction:item?.direction||'Increase'};}
}
