import { Goal, GoalDraft, GoalPortfolio, InitiativeOption, KeyResult, KeyResultDraft } from './goal.models';
export const GOAL_STATUSES=['Draft','Active','Paused','Completed','Cancelled'] as const;
export const GOAL_HEALTH=['NoUpdate','OnTrack','AtRisk','OffTrack'] as const;
export function quarter():{start:string;end:string}{const n=new Date(),m=Math.floor(n.getMonth()/3)*3;return{start:key(new Date(n.getFullYear(),m,1)),end:key(new Date(n.getFullYear(),m+3,0))};}
export function goalDraft(item?:Goal):GoalDraft{const q=quarter();return{id:item?.id,name:item?.name??'',description:item?.description??'',periodStart:item?.periodStart??q.start,periodEnd:item?.periodEnd??q.end,viewerUserIds:[...(item?.viewerUserIds??[])],initiativeKeys:(item?.initiativeLinks??[]).map(x=>`${x.portfolioId}:${x.initiativeId}`),projectIds:[...(item?.projectIds??[])],version:item?.version};}
export function keyResultDraft(owner:string,item?:KeyResult):KeyResultDraft{return{id:item?.id,name:item?.name??'',description:item?.description??'',ownerUserId:item?.ownerUserId??owner,baselineValue:item?.baselineValue??0,targetValue:item?.targetValue??100,initialValue:item?.currentValue??0,unit:item?.unit??'%',direction:item?.direction??'Increase'};}
export function goalError(d:GoalDraft):string|null{if(!d.name.trim())return'Hedef adı gereklidir.';if(!d.periodStart||!d.periodEnd)return'Hedef dönemi başlangıç ve bitiş tarihi gerektirir.';return d.periodEnd<d.periodStart?'Hedef dönemi başlangıçtan önce bitemez.':null;}
export function keyResultError(d:KeyResultDraft):string|null{if(!d.name.trim())return'Key result adı gereklidir.';if(!d.ownerUserId)return'Key result sahibi seçin.';if(!d.unit.trim())return'Ölçüm birimi gereklidir.';if(![d.baselineValue,d.targetValue,d.initialValue].every(Number.isFinite))return'Ölçüm değerleri sayısal olmalıdır.';if(d.baselineValue===d.targetValue)return'Baseline ve target farklı olmalıdır.';if(d.direction==='Increase'&&d.targetValue<d.baselineValue)return'Artış hedefinde target baseline değerinden büyük olmalıdır.';if(d.direction==='Decrease'&&d.targetValue>d.baselineValue)return'Azalış hedefinde target baseline değerinden küçük olmalıdır.';return null;}
export function updateError(note:string,confidence:number|null):string|null{if(!note.trim())return'Güncelleme notu gereklidir.';return confidence!=null&&(confidence<0||confidence>100)?'Güven 0 ile 100 arasında olmalıdır.':null;}
export function initiativeOptions(items:readonly GoalPortfolio[]):readonly InitiativeOption[]{return items.flatMap(p=>p.initiatives.map(i=>({key:`${p.id}:${i.id}`,portfolioId:p.id,initiativeId:i.id,label:`${p.name} · ${i.name}`})));}
export function links(keys:readonly string[],options:readonly InitiativeOption[]){return [...new Set(keys)].map(k=>options.find(x=>x.key===k)).filter((x):x is InitiativeOption=>!!x).map(({portfolioId,initiativeId})=>({portfolioId,initiativeId}));}
export function statusLabel(v:string){return({Draft:'Taslak',Active:'Aktif',Paused:'Duraklatıldı',Completed:'Tamamlandı',Cancelled:'İptal'} as Record<string,string>)[v]??v;}
export function healthLabel(v:string){return({NoUpdate:'Güncelleme yok',OnTrack:'Yolunda',AtRisk:'Riskli',OffTrack:'Raydan çıktı'} as Record<string,string>)[v]??v;}
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
