namespace Zumbo.ArchitectureTests.RefactorValidation;

public sealed class RefactorSemanticPreservationTests
{
    private static readonly IReadOnlyDictionary<string, string> AcceptedBodyDifferences =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Zumbo.Api|ApiHostRegistration|method:AddZumboHost:(thisWebApplicationBuilderbuilder):WebApplicationBuilder"] =
                "The composition root now delegates, in original order, to responsibility-specific Configure* partial methods; the local dependency-health timeout hardening is classified separately in the runtime contract audit.",
            ["Zumbo.Api|AutomationEndpoints|method:AddAutomationEngine:(thisIServiceCollectionservices,IConfiguration?configuration=null):IServiceCollection"] =
                "Automation run query, replay, retry, resume, execution, action-execution, and schedule-claim handlers are registered alongside the compatibility service while hosted-service and existing automation registrations remain unchanged under the exact runtime contract audit.",
            ["Zumbo.Api|AutomationRuntimeHostedService|method:ProcessIterationAsync:(CancellationTokenct):Task"] =
                "The automation runtime resolves independent execution, retry, resume, schedule-claim, and claim-completion handlers while preserving immutable snapshots, batch clamping, ordering, actor context, transaction boundaries, logging, and schedule processing.",
            ["Zumbo.Api|AutomationEndpoints|method:MapAutomationEndpoints:(thisRouteGroupBuilderapi):void"] =
                "Automation run query and replay routes resolve independent feature handlers while preserving routes, request binding, authorization, response mapping, and transaction filtering under the exact runtime contract audit.",
            ["Zumbo.Api|CapacityPlanningEndpoints|method:AddCapacityPlanningModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "The capacity-planning composition keeps the compatibility service and adds archive, single-plan, list, sharing, save, snapshot and scenario handlers plus their shared access policy as scoped self-services under the exact runtime contract audit.",
            ["Zumbo.Api|CapacityPlanningEndpoints|method:MapCapacityPlanningEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The capacity-plan archive, single-plan read, list, sharing, create, update, snapshot and scenario routes resolve independent handlers while preserving routes, authorization, transaction filtering, paging and archive binding, report rate limiting, correlation IDs, response mapping, and compatibility facades under the exact runtime contract audit.",
            ["Zumbo.Api|DevelopmentIntegrationEndpoints|method:MapDevelopmentIntegrationEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The connection-create/list/read/disconnect/delete, connection-mapping create/list/delete and work-item discovery, work-item-link listing/creation/deletion, webhook reception, credential-rotation, webhook-secret-rotation, provider-health, and repository-discovery routes resolve independent handlers while preserving routes, authorization, rate limiting, request binding, correlation IDs, and response mapping under the exact runtime contract audit.",
            ["Zumbo.Api|WorkItemEndpoints|method:MapWorkItemEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The route host now delegates each original mapping statement to a route-specific Map* partial method; HTTP route, metadata, authorization, request, response, and handler equivalence is verified by the runtime contract audit.",
            ["Zumbo.Api|IdentityEndpoints|method:AddIdentityModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Identity handler registrations remain scoped but now use explicit factories so the composition root selects port-focused vertical-slice constructors while legacy constructors remain available for source compatibility.",
            ["Zumbo.Api|IdentityEndpoints|method:MapIdentityEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The login route now resolves the independent Login handler while preserving its HTTP route, rate limiting, request binding, and response mapping through the exact runtime contract audit.",
            ["Zumbo.Persistence.PostgreSql|Zumbo.Persistence.PostgreSql.PostgreSqlMigrationRunner|method:BuildMigrations:():IReadOnlyList<Migration>"] =
                "Migration SQL constants moved from one method body to private fields while the ordered 37 Migration.Create calls remain in BuildMigrations; IDs, names, SQL, and checksums are verified by the runtime contract audit.",
            ["Zumbo.BuildingBlocks.Infrastructure|Zumbo.BuildingBlocks.Infrastructure.Search.OpenSearchWorkItemSearchIndex|method:InitializeAsync:(CancellationTokencancellationToken=default):Task"] =
                "Initialization now detects the pre-alias concrete index layout and delegates to a lossless, count-verified reindex migration before atomically installing the write alias; unit and live runtime checks cover both success and fail-closed behavior.",
            ["Zumbo.Api|MongoMigrationRunner|method:ApplyIndexesAsync:(stringmigrationId,IReadOnlyList<MongoIndexSpecification>indexes,CancellationTokencancellationToken):Task<MongoMigrationOutcome>"] =
                "Index application preserves catalog checksums while accepting semantically equivalent legacy names and skipping superseded identity and notification definitions whose dedicated later migrations own the valid replacements.",
            ["Zumbo.Api|MongoMigrationRunner|method:RunAsync:(CancellationTokencancellationToken=default):Task<MongoMigrationRunReport>"] =
                "Startup now always runs idempotent compatibility migrations that normalize legacy user document versions and remove infrastructure-only migration markers; optional high-volume business backfills remain explicitly gated.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:RegisterAsync:(RegisterUserRequestrequest,CancellationTokenct):Task<AuthResponse>"] =
                "The compatibility facade delegates registration to the port-focused RegisterUser slice; the original public signature remains available and registration behavior is covered by focused unit and API tests.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:LoginAsync:(LoginRequestrequest,CancellationTokenct):Task<AuthResponse>"] =
                "The compatibility facade delegates login to the port-focused Login handler while preserving its public signature, lockout retries, MFA flow, and token issuance behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:LogoutAsync:(LogoutRequestrequest,CancellationTokenct):Task<LogoutResponse>"] =
                "The compatibility facade delegates logout to the port-focused Logout handler while preserving idempotency, retry, legacy-session import, and all-session revocation behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:RefreshAsync:(RefreshTokenRequestrequest,CancellationTokenct):Task<AuthResponse>"] =
                "The compatibility facade delegates token refresh to the port-focused RefreshToken handler while preserving conflict retries, rotation, reuse detection, legacy-session import, and client metadata behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:ChangePasswordAsync:(ChangePasswordRequestrequest,stringcorrelationId,CancellationTokenct):Task<AuthResponse>"] =
                "The compatibility facade delegates password changes to the port-focused handler while preserving current-user checks, password policy, session revocation, token issuance, security-stamp rotation, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:ForgotPasswordAsync:(ForgotPasswordRequestrequest,CancellationTokenct):Task<PasswordResetRequestedResponse>"] =
                "The compatibility facade delegates password-reset requests to the port-focused handler while preserving input validation, account-enumeration resistance, token generation, expiry clamping, persistence, and notification behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:ResetPasswordAsync:(ResetPasswordRequestrequest,stringcorrelationId,CancellationTokenct):Task<PasswordResetResponse>"] =
                "The compatibility facade delegates password-reset completion to the port-focused handler while preserving token validation, password policy, lockout clearing, session revocation, concurrency masking, security-stamp rotation, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:ListSessionsAsync:(string?currentSessionId,CancellationTokenct):Task<IReadOnlyList<SessionResponse>>"] =
                "The compatibility facade delegates owned-session listing to the port-focused query handler while preserving current-user resolution, tenant ownership, session projection, ordering, and current-session identification.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:RevokeSessionAsync:(stringsessionId,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates owned-session revocation to the port-focused command handler while preserving validation, tenant ownership, idempotency, optimistic-concurrency retries, conflict behavior, and audit emission.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:GetMfaStatusAsync:(CancellationTokenct):Task<MfaStatusResponse>"] =
                "The compatibility facade delegates MFA status retrieval to the port-focused query handler while preserving authenticated-user resolution, enabled state, and remaining recovery-code count.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:BeginMfaSetupAsync:(BeginMfaSetupRequestrequest,stringcorrelationId,CancellationTokenct):Task<BeginMfaSetupResponse>"] =
                "The compatibility facade delegates MFA setup initiation to the port-focused handler while preserving password verification, enabled-state guard, protected pending-secret persistence, ten-minute expiry, provisioning URI, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:ConfirmMfaSetupAsync:(ConfirmMfaSetupRequestrequest,stringcorrelationId,CancellationTokenct):Task<ConfirmMfaSetupResponse>"] =
                "The compatibility facade delegates MFA setup confirmation to the port-focused handler while preserving pending-secret expiry cleanup, TOTP verification, recovery-code generation, security-stamp rotation, transactional session revocation, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:DisableMfaAsync:(DisableMfaRequestrequest,stringcorrelationId,CancellationTokenct):Task<MfaStatusResponse>"] =
                "The compatibility facade delegates MFA disablement to the port-focused handler while preserving password and MFA verification, recovery-code consumption, secret cleanup, security-stamp rotation, transactional session revocation, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:RegenerateMfaRecoveryCodesAsync:(RegenerateMfaRecoveryCodesRequestrequest,stringcorrelationId,CancellationTokenct):Task<RegenerateMfaRecoveryCodesResponse>"] =
                "The compatibility facade delegates MFA recovery-code regeneration to the port-focused handler while preserving password and MFA verification, prior recovery-code consumption, eight-code replacement, security-stamp rotation, transactional session revocation, and audit behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:DeactivateAsync:(DeactivateAccountRequestrequest,CancellationTokenct):Task<AccountStatusResponse>"] =
                "The compatibility facade delegates account deactivation to the port-focused handler while preserving password verification, inactive-state transition, security-stamp rotation, legacy refresh cleanup, and transactional session revocation.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:GetAsync:(stringrunId,CancellationTokenct):Task<AutomationRunResponse>"] =
                "The compatibility facade delegates automation-run retrieval to the RunQueries handler while preserving not-found masking, project-view authorization, tenant isolation, ordered step mapping, and version projection.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:ListAsync:(stringprojectId,string?ruleId,string?status,intpage,intpageSize,CancellationTokenct):Task<AutomationRunPageResponse>"] =
                "The compatibility facade delegates automation-run listing to the RunQueries handler while preserving project-view authorization, tenant and optional filters, page normalization, descending creation order, total count, and response mapping.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:ReplayAsync:(stringrunId,stringcorrelationId,CancellationTokenct):Task<AutomationRunResponse>"] =
                "The compatibility facade delegates replay to the RunReplay handler while preserving distributed locking, manage authorization, tenant masking, dead-letter guard, retry reset, failed-step reset, optimistic concurrency, audit emission, and response mapping.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:ResumeAsync:(stringrunId,boolactorAvailable,CancellationTokenct):Task<AutomationRunResponse>"] =
                "The compatibility facade delegates resume to the RunResume handler while preserving locking, retry timing, rule-version lookup, actor availability handling, action progress persistence, retry backoff, dead-lettering, and response mapping.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:ClaimDueSchedulesAsync:(intpageSize,CancellationTokenct):Task<IReadOnlyCollection<AutomationScheduleDispatch>>"] =
                "The compatibility facade delegates schedule claiming to the ScheduleClaims handler while preserving due filtering, page clamping, per-rule locking, revalidation, published schedule checks, five-minute claims, optimistic concurrency, ordering, and dispatch projection.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:CompleteScheduleClaimAsync:(stringruleId,DateTimeOffsetscheduledForUtc,stringclaimToken,CancellationTokenct):Task<bool>"] =
                "The compatibility facade delegates claim completion to the ScheduleClaims handler while preserving per-rule locking, stale-token rejection, published schedule validation, drift-free next-run calculation, claim cleanup, optimistic concurrency, and boolean outcome.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.AutomationExecutionService|method:ExecuteAsync:(AutomationExecutionContextcontext,CancellationTokenct):Task<IReadOnlyCollection<AutomationRunResponse>>"] =
                "The compatibility facade delegates execution to the RunExecution handler while preserving validation, cursor-based rule matching, deterministic deduplication, run creation, skip guards, condition evaluation, hourly limits, action execution, retry behavior, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:ArchiveAsync:(stringplanId,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates capacity-plan archiving to its command handler while preserving authenticated actor resolution, tenant masking, owner and viewer semantics, archive timestamp, expected-version consumption, optimistic concurrency, audit content, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:GetAsync:(stringplanId,boolincludeArchived,CancellationTokenct):Task<CapacityPlanResponse>"] =
                "The compatibility facade delegates single-plan retrieval to its query handler while preserving authenticated actor resolution, archived filtering, tenant and viewer masking, project visibility, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:GetSnapshotAsync:(stringplanId,CancellationTokenct):Task<CapacitySnapshotResponse>"] =
                "The compatibility facade delegates snapshot retrieval to its query handler while preserving actor and tenant resolution, archived and viewer masking, project access filtering, source bounds, partial-state reporting, calculation formulas, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:ListAsync:(boolincludeArchived,intpage,intpageSize,CancellationTokenct):Task<CapacityPlanPageResponse>"] =
                "The compatibility facade delegates capacity-plan listing to its query handler while preserving actor resolution, page normalization, 500-item candidate bound, tenant, archive, owner and viewer filtering, project visibility, descending update ordering, response projection, total count, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:PreviewScenarioAsync:(stringplanId,CapacityScenarioRequestrequest,CancellationTokenct):Task<CapacityScenarioResponse>"] =
                "The compatibility facade delegates scenario preview to its query handler while preserving actor and tenant resolution, archived masking, owner enforcement, allocation normalization and bounds, shared source loading, baseline and candidate calculations, non-persistence, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:ShareAsync:(stringplanId,ShareCapacityPlanRequestrequest,stringcorrelationId,CancellationTokenct):Task<CapacityPlanResponse>"] =
                "The compatibility facade delegates capacity-plan sharing to its command handler while preserving actor and tenant resolution, owner and viewer masking, viewer normalization and limit, owner exclusion, directory validation, timestamp, expected-version consumption, optimistic concurrency, audit values, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:SaveAsync:(string?planId,SaveCapacityPlanRequestrequest,stringcorrelationId,CancellationTokenct):Task<CapacityPlanResponse>"] =
                "The compatibility facade delegates capacity-plan creation and update to its command handler while preserving actor and tenant resolution, owner masking, complete request normalization and limits, directory validation, document projection, create/update branching, timestamps, expected-version consumption, optimistic concurrency, audit values, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CapacityPlanningService|method:ToResponse:(CapacityPlanDocumentplan,stringuserId):CapacityPlanResponse"] =
                "The compatibility mapper delegates to the feature-owned response mapper while preserving every response field, UTC date conversion, collection projection, editability, archive state, timestamp, and version.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:ListAsync:(CancellationTokenct):Task<IReadOnlyList<WebhookSubscriptionResponse>>"] =
                "The compatibility facade delegates subscription listing to its query handler while preserving organization resolution, manage authorization, 200-item cursor traversal, response projection, ordering, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:GetAsync:(stringid,CancellationTokenct):Task<WebhookSubscriptionResponse>"] =
                "The compatibility facade delegates subscription reading to its query handler while preserving organization resolution, manage authorization, tenant ownership filtering, not-found contract, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:GetMetricsAsync:(CancellationTokenct):Task<WebhookDeliveryMetrics>"] =
                "The compatibility facade delegates delivery metrics to its query handler while preserving organization resolution, manage authorization, status filters, four count queries, oldest-pending ordering, captured clock value, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:ListDeliveriesAsync:(stringsubscriptionId,string?cursor,intpageSize,CancellationTokenct):Task<WebhookDeliveryPage>"] =
                "The compatibility facade delegates delivery listing to its query handler while preserving organization resolution, manage authorization, subscription ownership, cursor normalization, page-size bounds, delivery filtering, response projection, paging cursor, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:GetDeliveryAsync:(stringid,CancellationTokenct):Task<WebhookDeliveryResponse>"] =
                "The compatibility facade delegates delivery reading to its query handler while preserving organization resolution, manage authorization, tenant ownership filtering, delivery not-found contract, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:ReplayAsync:(stringid,CancellationTokenct,string?correlationId=null):Task<WebhookDeliveryResponse>"] =
                "The compatibility facade delegates dead-letter replay to its command handler while preserving organization resolution, manage authorization, dead-letter filtering, state and attempt reset, clock values, lease cleanup, optimistic replacement, conflict and not-found contracts, audit values, correlation fallback, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:SetActiveAsync:(stringid,boolactive,SetWebhookSubscriptionStateRequestrequest,CancellationTokenct,string?correlationId=null):Task<WebhookSubscriptionResponse>"] =
                "The compatibility facade delegates subscription state changes to its command handler while preserving organization resolution, manage authorization, ownership filtering, requested state, timestamp, expected-version replacement, conflict and not-found contracts, audit action and values, correlation fallback, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:UpdateAsync:(stringid,UpdateWebhookSubscriptionRequestrequest,CancellationTokenct,string?correlationId=null):Task<WebhookSubscriptionResponse>"] =
                "The compatibility facade delegates subscription updates to its command handler while preserving organization resolution, manage authorization, ownership filtering, old audit snapshot timing, target/name/scope validation and normalization order, target policy, timestamp, expected-version replacement, conflict and not-found contracts, audit values, correlation fallback, response projection, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:CreateAsync:(CreateWebhookSubscriptionRequestrequest,CancellationTokenct,string?correlationId=null):Task<WebhookSecretReceipt>"] =
                "The compatibility facade delegates subscription creation to its command handler while preserving organization and user requirements, manage authorization, secret generation and fingerprinting, clock capture, target/name/scope validation and normalization order, target policy, secret protection, persistence, audit values, correlation fallback, receipt mapping, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:RotateSecretAsync:(stringid,RotateWebhookSecretRequestrequest,CancellationTokenct,string?correlationId=null):Task<WebhookSecretReceipt>"] =
                "The compatibility facade delegates subscription secret rotation to its command handler while preserving organization resolution, manage authorization, ownership filtering, secret generation, previous-secret fields, clamped overlap, secret protection and fingerprinting, version and timestamp updates, optimistic replacement, conflict and not-found contracts, audit values, correlation fallback, receipt mapping, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:QueueTestDeliveryAsync:(stringid,CancellationTokenct,string?correlationId=null):Task<WebhookDeliveryResponse>"] =
                "The compatibility facade delegates test-delivery queueing to its command handler while preserving organization resolution, manage authorization, ownership and active-state checks, clock capture, random event identity, payload schema and serialization, payload hashing, pending delivery persistence, audit values, correlation fallback, response mapping, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:QueueAsync:(stringsourceEventId,stringorganizationId,WorkItemWebhookEventmessage,CancellationTokenct):Task"] =
                "The compatibility facade delegates durable work-item event queueing to its handler while preserving event-scope mapping and rejection, cursor-based active subscription traversal, exact scope filtering, deterministic delivery identity, immutable payload schema and serialization, payload hashing, clock capture, delivery persistence, idempotent conflict handling, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemWebhookService|method:DispatchAsync:(intbatchSize,stringworkerId,CancellationTokenct):Task<int>"] =
                "The compatibility facade delegates delivery dispatch to its handler while preserving enabled-state short circuit, due and expired-lease selection, batch bounds, lease claim predicates and values, subscription availability, target validation, current and previous signatures, sender request, success finalization, retry and dead-letter behavior, jitter policy, cancellation handling, delivered count, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:GetAsync:(stringid,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates single work-item reads to the port-focused query slice while preserving the active-record filter, not-found contract, both existing view-permission checks, organization-scoped activity hydration, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:ArchiveAsync:(stringid,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates work-item archiving to the port-focused command slice while preserving active-record reads, view and delete authorization, organization-scoped activity hydration, project-structure locking, active-child rejection, WIP release, timestamp and optimistic-version persistence, search deletion, audit, watcher activity, realtime publication, cache invalidation, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:RestoreAsync:(stringid,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates work-item restoration to the port-focused command slice while preserving archived-record reads and not-found masking, view and delete authorization, organization-scoped activity hydration, project-structure and WIP placement locking, board placement and capacity checks, WIP reservation, rank allocation, timestamp and optimistic-version persistence, search indexing, audit, watcher activity, realtime publication, cache invalidation, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:AddLabelAsync:(stringid,AddLabelRequestrequest,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates label addition to the port-focused command slice while preserving trim and required validation, active-record lookup, view and update authorization, organization-scoped activity hydration, case-insensitive duplicate rejection, timestamp and optimistic-version persistence, search indexing, deterministic mutation identifiers, collaboration activity and watcher notification, automation event fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:RemoveLabelAsync:(stringid,stringlabel,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates label removal to the port-focused command slice while preserving the untrimmed route value, active-record lookup, view and update authorization, organization-scoped activity hydration, case-insensitive removal, missing-label error contract, timestamp and optimistic-version persistence, search indexing, deterministic mutation identifiers, collaboration activity and watcher notification, automation event fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:AddChecklistItemAsync:(stringid,AddChecklistItemRequestrequest,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates checklist-item addition to the port-focused command slice while preserving text trimming without new blank-text rejection, active-record lookup, view and update authorization, organization-scoped activity hydration, generated checklist identity, timestamp and optimistic-version persistence, checklist-item activity identity, watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:CompleteChecklistItemAsync:(stringid,stringitemId,CompleteChecklistItemRequestrequest,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates checklist-item completion and reopening to the port-focused command slice while preserving active-record lookup, view and update authorization, organization-scoped activity hydration, exact checklist-item lookup and missing-item contract, requested completion state, timestamp and optimistic-version persistence, timestamp-derived mutation identity, completed-versus-reopened activity detail, watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:AddWorkLogAsync:(stringid,AddWorkLogRequestrequest,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates work-log creation to the port-focused command slice while preserving hours validation, active-record lookup, view and WorkLogCreate authorization, organization-scoped activity hydration, legacy embedded-activity migration and optimistic persistence, work-log identity and timestamp creation, separated work-log persistence, project-cache invalidation, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SetPlanningAsync:(stringid,SetWorkItemPlanningRequestrequest,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates planning updates to the port-focused command slice while preserving active-record lookup, view and update authorization, organization-scoped activity hydration, optional sprint-policy fallback and transition check, aggregate planning rules and timestamp, optimistic persistence, search indexing, timestamp-derived mutation identity, collaboration activity and watcher notification, project-cache invalidation, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:ClearAssigneeAsync:(stringid,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates assignee clearing to the port-focused command slice while preserving active-record lookup, view and assign authorization, organization-scoped activity hydration, no-op response when already unassigned, previous-assignee capture, timestamp and optimistic-version persistence, search indexing, audit payload, collaboration activity and watcher notification, realtime publication, project-cache invalidation, automation fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:AssignAsync:(stringid,AssignWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates assignment to the port-focused command slice while preserving active-record lookup, view and assign authorization, organization-scoped activity hydration, team eligibility checks, previous and requested assignee values, timestamp and optimistic-version persistence, search indexing, audit payload, assignee notification, collaboration activity and watcher exclusion, realtime publication, project-cache invalidation, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SetTeamAsync:(stringid,SetWorkItemTeamRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates team updates to the port-focused command slice while preserving active-record lookup, view and update authorization, organization-scoped activity hydration, optional team normalization, team and assignee eligibility, unchanged-team conflict, previous and requested team values, timestamp and optimistic-version persistence, audit payload, collaboration activity and watcher notification, realtime publication, project-cache invalidation, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SetCustomFieldsAsync:(stringid,SetWorkItemCustomFieldsRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates custom-field updates to the port-focused command slice while preserving active-record lookup, view and update authorization, organization-scoped activity hydration, type-schema validation, previous-value serialization, normalized issue type and schema version, timestamp and optimistic-version persistence, search indexing, audit payload, collaboration activity and watcher notification, realtime publication, project-cache invalidation, automation identity, fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:RequestApprovalAsync:(stringid,RequestWorkItemApprovalRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates approval requests to the port-focused command slice while preserving active-record lookup, view and move authorization, organization-scoped hydration, legacy activity separation, target normalization and validation, workflow transition policy, approval-required and active-approval conflicts, clock-derived request and expiry values, requester fallback, optimistic persistence, separated approval persistence, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:DecideApprovalAsync:(stringid,stringapprovalId,DecideWorkItemApprovalRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates approval decisions to the port-focused command slice while preserving active-record lookup, view and approve authorization, organization-scoped hydration, legacy activity separation, approval lookup and pending-state contract, clock-derived expiry persistence and conflict, self-approval guard, note normalization and length validation, decision fields, optimistic persistence, separated approval activity update, audit payload, collaboration activity and watcher notification, requester notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:UpdateAsync:(stringid,UpdateWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates core field updates to the port-focused command slice while preserving active-record lookup, view and update authorization, organization-scoped hydration, old-value capture, title validation and normalization, optional description and priority handling, due-reminder reset, clock timestamp, optimistic persistence, search indexing, audit values, collaboration activity and watcher notification, realtime publication, project-cache invalidation, automation identity, fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:MoveAsync:(stringid,MoveWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates status transitions to the port-focused command slice while preserving active-record double reads, view and move authorization, project and placement locking, organization-scoped hydration, legacy activity separation, target normalization, aggregate and workflow policy, board placement and rank, done-category dependency checks, WIP capacity or projection reservation, actor and clock values, optimistic persistence, approval and timeline activity updates, search indexing, movement and workflow-automation audit, collaboration activity and watcher status notification, realtime publication, project-cache invalidation, automation identity, fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:ReorderAsync:(stringid,ReorderWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates rank changes to the port-focused command slice while preserving active-record double reads, view and move authorization, project-structure locking, organization-scoped hydration, rank resolution and compaction behavior, previous rank capture, clock timestamp, optimistic and separated persistence, invariant audit values, collaboration activity and watcher notification, realtime publication, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:AddCommentAsync:(stringid,AddCommentRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates comment creation to the port-focused command slice while preserving body, mention and idempotency-key normalization, active-record lookup, view and comment-create authorization, organization-scoped hydration, mention validation, legacy activity separation, deterministic comment identity, idempotent replay and key-reuse conflict behavior, comment limit, actor and clock values, separated comment persistence, audit payload, mention notification exclusion and identity, collaboration activity and watcher exclusions, automation identity, fields and chain context, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:EditCommentAsync:(stringid,stringcommentId,EditCommentRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates comment editing to the port-focused command slice while preserving body normalization, active-record lookup, view and comment-create authorization, organization-scoped hydration, legacy activity separation, exact comment lookup and missing contract, author ownership, unchanged and history-limit conflicts, old body capture, clock-derived revision and edited timestamps, revision actor fallback, separated revision creation and comment update, audit payload, collaboration activity and watcher notification identity, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:DeleteCommentAsync:(stringid,stringcommentId,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates comment deletion to the port-focused command slice while preserving active-record lookup, view and comment-create authorization, organization-scoped hydration, legacy activity separation, exact comment lookup and missing contract, author ownership, separated comment lookup and deletion including revisions, in-memory response removal, audit payload, collaboration activity and watcher notification identity, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SetParentAsync:(stringid,SetWorkItemParentRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates parent changes to the port-focused command slice while preserving active-record double reads, view and update authorization, organization-scoped hydration, project-structure locking, hierarchy-level rules, parent project, completion and board constraints, graph cycle and child-limit validation, unchanged-parent conflict, clock timestamp, optimistic and separated persistence, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:LinkAsync:(stringid,LinkWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates relation creation to the port-focused command slice while preserving active-record double reads, view and link authorization, organization-scoped hydration, project-structure locking, relation-type defaults and normalization, self-link and same-project validation, duplicate relation conflict, canonical graph insertion and cycle guards before document mutation, clock timestamp, optimistic and separated persistence, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:UnlinkAsync:(stringid,stringrelatedWorkItemId,stringrelationType,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates relation deletion to the port-focused command slice while preserving active-record double reads, view and link authorization, organization-scoped hydration, project-structure locking, relation-type defaults and normalization, exact case-insensitive document removal, missing-relation contract, graph removal before clock update and persistence, optimistic and separated persistence, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:OpenAttachmentAsync:(stringid,stringattachmentId,CancellationTokenct):Task<AttachmentFile>"] =
                "The compatibility facade delegates attachment opening to the port-focused query slice while preserving active-record lookup, repeated view authorization, organization-scoped hydration, legacy embedded fallback, separated attachment lookup, exact not-found contracts, clean security-state gate and conflict code, storage path, content type and checksum forwarding, stream and file metadata projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:UploadAttachmentAsync:(stringid,Streamcontent,stringfileName,stringcontentType,longdeclaredSizeBytes,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates attachment upload to the port-focused command slice while preserving size and filename validation, active-record double reads, view and attachment-create authorization, organization-scoped hydration, project locking, legacy activity separation, attachment limit, storage save, exact document projection, optimistic and separated persistence, storage compensation and warning logging, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:DeleteAttachmentAsync:(stringid,stringattachmentId,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The compatibility facade delegates attachment deletion to the port-focused command slice while preserving active-record double reads, view and attachment-delete authorization, organization-scoped hydration, project locking, legacy activity separation, exact separated attachment lookup and deletion, in-memory projection removal, storage deletion, persistence restore compensation and warning logging, exact document reconstruction on failure, audit payload, collaboration activity and watcher notification, response projection, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SendDueDateRemindersAsync:(inthorizonHours,CancellationTokenct):Task<int>"] =
                "The compatibility facade delegates due-date reminder dispatch to the port-focused command slice while preserving horizon clamping, global and per-item locking, bounded due-date ordering, active incomplete assigned filtering, assignee view authorization and skip contracts, stale-candidate rechecks, due-date-derived deduplication, notification ordering, separate clock reads, optimistic separated persistence, sent count, cancellation, and public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:ProjectSummaryAsync:(stringprojectId,CancellationTokenct):Task<ProjectSummaryResponse>"] =
                "The compatibility facade delegates project-summary data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:ProjectSummarySnapshotAsync:(stringprojectId,CancellationTokenct):Task<WorkItemReportSnapshot<ProjectSummaryResponse>>"] =
                "The compatibility facade delegates project-summary snapshot retrieval to the port-focused query slice while preserving view authorization, tenant scope, exact cache key and clamped TTL, one clock boundary, total, completed, active-status and overdue count filters, checked integer conversion, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:StatusDistributionAsync:(stringprojectId,CancellationTokenct):Task<IReadOnlyList<StatusDistributionResponse>>"] =
                "The compatibility facade delegates status-distribution data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:StatusDistributionSnapshotAsync:(stringprojectId,CancellationTokenct):Task<WorkItemReportSnapshot<IReadOnlyList<StatusDistributionResponse>>>"] =
                "The compatibility facade delegates status-distribution snapshot retrieval to the port-focused query slice while preserving view authorization, exact active-item filter and cursor paging, cache key and clamped TTL, ordinal status ordering, exact grouping and count projection, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:UserWorkloadAsync:(stringprojectId,CancellationTokenct):Task<IReadOnlyList<UserWorkloadResponse>>"] =
                "The compatibility facade delegates user-workload data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:UserWorkloadSnapshotAsync:(stringprojectId,CancellationTokenct):Task<WorkItemReportSnapshot<IReadOnlyList<UserWorkloadResponse>>>"] =
                "The compatibility facade delegates user-workload snapshot retrieval to the port-focused query slice while preserving view authorization, organization-scoped activity reads, active-item cursor paging, cache key and clamped TTL, one clock boundary, non-empty assignee grouping and ordinal ordering, open and overdue count predicates, activity-storage version fallback, logged-hours aggregation, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:DueDateRisksAsync:(stringprojectId,intdays,CancellationTokenct):Task<IReadOnlyList<DueDateRiskResponse>>"] =
                "The compatibility facade delegates due-date-risk data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:DueDateRisksSnapshotAsync:(stringprojectId,intdays,CancellationTokenct):Task<WorkItemReportSnapshot<IReadOnlyList<DueDateRiskResponse>>>"] =
                "The compatibility facade delegates due-date-risk snapshot retrieval to the port-focused query slice while preserving view authorization, days clamping, exact cache-key shape and TTL clamp, one clock boundary, active incomplete due-date filter and cursor paging, due-date and ordinal ID ordering, exact response projection, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:FlowTimeAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<FlowTimeReportResponse>"] =
                "The compatibility facade delegates flow-time data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:FlowTimeSnapshotAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<WorkItemReportSnapshot<FlowTimeReportResponse>>"] =
                "The compatibility facade delegates flow-time snapshot retrieval to the port-focused query slice while preserving view authorization, default and validated date range, exact validation messages, UTC day boundaries, cache key and TTL clamp, completed-item cursor paging, organization-scoped activity timeline and legacy fallback, reopened-work cycle start selection, lead and cycle sample calculations, average and median rounding, exact response projection, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:CompletionRateAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<TaskCompletionRateResponse>"] =
                "The compatibility facade delegates completion-rate data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:CompletionRateSnapshotAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<WorkItemReportSnapshot<TaskCompletionRateResponse>>"] =
                "The compatibility facade delegates completion-rate snapshot retrieval to the port-focused query slice while preserving view authorization, default and validated date range, exact validation messages, UTC day boundaries, cache key and TTL clamp, created-item cursor paging, completion cutoff, empty-set behavior, two-decimal percentage, exact response projection, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:TeamPerformanceAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<IReadOnlyList<TeamPerformanceResponse>>"] =
                "The compatibility facade delegates team-performance data retrieval to the port-focused query slice while preserving snapshot data projection, cancellation, and the public signature.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:TeamPerformanceSnapshotAsync:(stringprojectId,DateOnly?from,DateOnly?to,CancellationTokenct):Task<WorkItemReportSnapshot<IReadOnlyList<TeamPerformanceResponse>>>"] =
                "The compatibility facade delegates team-performance snapshot retrieval to the port-focused query slice while preserving view authorization, default and validated date range, exact validation messages, UTC day boundaries, cache key and TTL clamp, team-policy call order, explicit team-assignment cursor paging, organization-scoped activity reads and legacy worklog fallback, team-name ordering, completion cutoff and percentage, average lead-time rounding, logged-hours aggregation, exact response projection, snapshot metadata, cancellation, and the public signature.",
            ["Zumbo.Api|DueDateReminderHostedService|method:ExecuteAsync:(CancellationTokenstoppingToken):Task"] =
                "The hosted service resolves the due-date reminder handler instead of the compatibility facade while preserving enablement, interval clamping, async scope, durable WorkItems transaction boundary, horizon binding, cancellation exit, iteration error logging, timer behavior, and hosted-service signature.",
            ["Zumbo.Api|WorkItemWebhookDeliveryAdapter|method:DeliverAsync:(stringsourceEventId,stringorganizationId,WorkItemWebhookEventmessage,CancellationTokencancellationToken):Task"] =
                "The adapter delegates durable queueing to QueueDeliveryHandler when composed through the new factory and retains WorkItemWebhookService delegation for callers using the preserved constructor; arguments, cancellation and behavior remain unchanged.",
            ["Zumbo.Api|WebhookDispatcherHostedService|method:ExecuteAsync:(CancellationTokenstoppingToken):Task"] =
                "The hosted service resolves DispatchDeliveriesHandler directly per scope while preserving enabled-state short circuit, timer interval, batch clamp, stable worker identity, cancellation handling, error logging, iteration cadence, primary constructor and hosted-service registration.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:CheckHealthAsync:(stringconnectionId,stringcorrelationId,CancellationTokenct):Task<DevelopmentHealthResponse>"] =
                "The compatibility facade delegates provider-health checks to the ProviderHealth handler while preserving tenant authorization, connection-state validation, provider probing, credential unprotection, health persistence, concurrency behavior, audit emission, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ListProviderRepositoriesAsync:(stringconnectionId,CancellationTokenct):Task<DevelopmentProviderRepositoryResult>"] =
                "The compatibility facade delegates repository discovery to its query handler while preserving tenant authorization, connected-state validation, credential unprotection, provider selection, item limits, and partial-result behavior.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ListAsync:(CancellationTokenct):Task<IReadOnlyCollection<DevelopmentConnectionResponse>>"] =
                "The compatibility facade delegates connection listing to its query handler while preserving tenant authorization, cursor paging, descending update ordering, required-scope projection, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:GetAsync:(stringconnectionId,CancellationTokenct):Task<DevelopmentConnectionResponse>"] =
                "The compatibility facade delegates connection reads to its query handler while preserving tenant authorization, cross-tenant not-found masking, required-scope projection, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:CreateAsync:(CreateDevelopmentConnectionRequestrequest,stringcorrelationId,CancellationTokenct):Task<DevelopmentConnectionReceipt>"] =
                "The compatibility facade delegates connection creation to its command handler while preserving tenant authorization, organization limits, provider and URL validation, credential protection, webhook-secret generation, fingerprints, persistence, audit content, and receipt mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:RotateCredentialAsync:(stringconnectionId,RotateDevelopmentCredentialRequestrequest,stringcorrelationId,CancellationTokenct):Task<DevelopmentConnectionResponse>"] =
                "The compatibility facade delegates credential rotation to its command handler while preserving tenant authorization, connected-state validation, token rules, credential protection, fingerprinting, health reset, optimistic concurrency, audit content, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:RotateWebhookSecretAsync:(stringconnectionId,DevelopmentVersionRequestrequest,stringcorrelationId,CancellationTokenct):Task<DevelopmentConnectionReceipt>"] =
                "The compatibility facade delegates webhook-secret rotation to its command handler while preserving tenant authorization, connected-state validation, random provider-specific secret generation, previous-secret grace state, protection, fingerprinting, versioning, optimistic concurrency, audit content, and receipt mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:DisconnectAsync:(stringconnectionId,DevelopmentVersionRequestrequest,stringcorrelationId,CancellationTokenct):Task<DevelopmentConnectionResponse>"] =
                "The compatibility facade delegates disconnect to its command handler while preserving tenant authorization, idempotency, lifecycle and secret cleanup, connection concurrency, paged active-mapping deactivation, mapping concurrency, audit content, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:DeleteConnectionAsync:(stringconnectionId,longexpectedVersion,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates permanent connection deletion to its command handler while preserving tenant authorization, pre-delete version validation, linked development-link, receipt, and mapping cleanup, conditional connection deletion, optimistic concurrency, and audit content.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ListMappingsAsync:(stringconnectionId,CancellationTokenct):Task<IReadOnlyCollection<DevelopmentRepositoryMappingResponse>>"] =
                "The compatibility facade delegates connection-mapping listing to its query handler while preserving tenant authorization, cross-tenant not-found masking, cursor paging, project/repository ordering, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:CreateMappingAsync:(stringconnectionId,CreateDevelopmentRepositoryMappingRequestrequest,stringcorrelationId,CancellationTokenct):Task<DevelopmentRepositoryMappingResponse>"] =
                "The compatibility facade delegates mapping creation to its command handler while preserving tenant and project authorization, connected-state and limit checks, duplicate rejection, project snapshots, field and repository URL validation, persistence, audit content, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:DeleteMappingAsync:(stringmappingId,longexpectedVersion,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates mapping deletion to its command handler while preserving tenant and project authorization, optimistic concurrency, linked-development-data cleanup, conditional deletion, audit content, and not-found masking.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ListWorkItemMappingsAsync:(stringworkItemId,CancellationTokenct):Task<IReadOnlyCollection<DevelopmentRepositoryMappingResponse>>"] =
                "The compatibility facade delegates work-item mapping discovery to its query handler while preserving archived-item masking, tenant and project authorization, cursor paging, active same-project filtering, repository ordering, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ListWorkItemLinksAsync:(stringworkItemId,CancellationTokenct):Task<IReadOnlyCollection<WorkItemDevelopmentLinkResponse>>"] =
                "The compatibility facade delegates work-item link listing to its query handler while preserving archived-item masking, tenant and project authorization, cursor paging, project/work-item filtering, connection-state projection, update ordering, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:CreateWorkItemLinkAsync:(stringworkItemId,CreateWorkItemDevelopmentLinkRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemDevelopmentLinkResponse>"] =
                "The compatibility facade delegates work-item link creation to its command handler while preserving archived-item masking, tenant and project authorization, mapping and connection checks, link limits, normalization, deterministic identity, idempotency, persistence, audit content, and response mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:DeleteWorkItemLinkAsync:(stringworkItemId,stringlinkId,longexpectedVersion,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates work-item link deletion to its command handler while preserving archived-item masking, tenant and project authorization, link ownership checks, optimistic concurrency, conditional deletion, audit content, and not-found masking.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ReceiveWebhookAsync:(stringconnectionId,DevelopmentWebhookRequestrequest,CancellationTokenct):Task<DevelopmentWebhookResult>"] =
                "The compatibility facade delegates webhook reception to its command handler while preserving payload limits, connection and signature verification, previous-secret grace behavior, expired-receipt cleanup, normalization, deterministic receipt identity, constant-time deduplication, delivery collision rejection, durable queueing, and result mapping.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.DevelopmentIntegrationService|method:ProcessWebhookAsync:(DevelopmentWebhookEventmessage,CancellationTokenct):Task"] =
                "The compatibility facade delegates webhook processing to its command handler while preserving receipt idempotency, connection lifecycle validation, repository mapping, event normalization, work-item reference resolution, deterministic link creation, stale-event protection, optimistic concurrency, receipt status updates, applied-link counts, and audit content.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.IdentityService|method:SearchUsersAsync:(string?search,CancellationTokenct):Task<IReadOnlyList<UserProfileResponse>>"] =
                "The compatibility facade delegates user search to its port-focused query slice while preserving the original public signature and tenant authorization behavior.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.RegisterUserHandler|method:HandleAsync:(RegisterUserRequestrequest,CancellationTokenct):Task<AuthResponse>"] =
                "The endpoint handler now selects the independent registration slice when composed from ports while retaining the original IdentityService constructor as a compatibility path.",
            ["Zumbo.Modules.Identity|Zumbo.Modules.Identity.SearchUsersHandler|method:HandleAsync:(SearchUsersQueryquery,CancellationTokenct):Task<IReadOnlyList<UserProfileResponse>>"] =
                "The endpoint handler now selects the independent user-search slice when composed from ports while retaining the original IdentityService constructor as a compatibility path.",
            ["Zumbo.Api|OrganizationsEndpoints|method:AddOrganizationsModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Organization create and list handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Organizations|Zumbo.Modules.Organizations.OrganizationService|method:CreateAsync:(CreateOrganizationRequestrequest,stringcorrelationId,CancellationTokenct):Task<OrganizationResponse>"] =
                "The compatibility facade delegates organization creation to the port-focused CreateOrganization slice while preserving its public signature and behavior.",
            ["Zumbo.Modules.Organizations|Zumbo.Modules.Organizations.OrganizationService|method:ListAsync:(CancellationTokenct):Task<IReadOnlyList<OrganizationResponse>>"] =
                "The compatibility facade delegates organization listing to the tenant-scoped ListOrganizations query slice while preserving its public signature.",
            ["Zumbo.Modules.Organizations|Zumbo.Modules.Organizations.CreateOrganizationHandler|method:HandleAsync:(CreateOrganizationRequestrequest,stringcorrelationId,CancellationTokenct):Task<OrganizationResponse>"] =
                "The endpoint handler selects the independent organization-creation slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Organizations|Zumbo.Modules.Organizations.ListOrganizationsHandler|method:HandleAsync:(ListOrganizationsQueryquery,CancellationTokenct):Task<IReadOnlyList<OrganizationResponse>>"] =
                "The endpoint handler selects the independent organization-list query slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Organizations|Zumbo.Modules.Organizations.OrganizationService|ctor:(IDocumentRepository<OrganizationDocument>organizations,IOrganizationMemberDirectorymemberDirectory,IDistributedLockProviderdistributedLockProvider,IOptions<DistributedLockOptions>distributedLockOptions,IClockclock,ICurrentUsercurrentUser,IOrganizationAuditWriteraudit,IExpectedVersionAccessor?expectedVersions=null,IOptions<OrganizationLifecycleOptions>?lifecycleOptions=null)"] =
                "The unchanged compatibility facade constructor now wires the port-focused create and list handlers from its existing dependencies; its public signature and all previous assignments remain intact.",
            ["Zumbo.Api|TeamsEndpoints|method:AddTeamsModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Team create and list handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Teams|Zumbo.Modules.Teams.TeamService|method:CreateAsync:(CreateTeamRequestrequest,stringcorrelationId,CancellationTokenct):Task<TeamResponse>"] =
                "The compatibility facade delegates team creation to the port-focused CreateTeam slice while preserving its public signature and behavior.",
            ["Zumbo.Modules.Teams|Zumbo.Modules.Teams.TeamService|method:ListAsync:(stringorganizationId,CancellationTokenct,boolarchived=false):Task<IReadOnlyList<TeamResponse>>"] =
                "The compatibility facade delegates team listing to the tenant-scoped ListTeams query slice while preserving its public signature.",
            ["Zumbo.Modules.Teams|Zumbo.Modules.Teams.CreateTeamHandler|method:HandleAsync:(CreateTeamRequestrequest,stringcorrelationId,CancellationTokenct):Task<TeamResponse>"] =
                "The endpoint handler selects the independent team-creation slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Teams|Zumbo.Modules.Teams.ListTeamsHandler|method:HandleAsync:(ListTeamsQueryquery,CancellationTokenct):Task<IReadOnlyList<TeamResponse>>"] =
                "The endpoint handler selects the independent team-list query slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Teams|Zumbo.Modules.Teams.TeamService|ctor:(IDocumentRepository<TeamDocument>teams,ITeamUserDirectoryuserDirectory,ITeamAuditWriteraudit,IClockclock,ICurrentUsercurrentUser,IExpectedVersionAccessor?expectedVersions=null,ITeamOrganizationDirectory?organizationDirectory=null,ITeamInvitationNotifier?invitationNotifier=null)"] =
                "The unchanged compatibility facade constructor now wires the port-focused create and list handlers from its existing dependencies; its public signature and all previous assignments remain intact.",
            ["Zumbo.Api|ProjectsEndpoints|method:AddProjectsModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Project create and list handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Projects|Zumbo.Modules.Projects.ProjectService|method:CreateAsync:(CreateProjectRequestrequest,stringcorrelationId,CancellationTokenct):Task<ProjectResponse>"] =
                "The compatibility facade delegates project creation to the port-focused CreateProject slice while preserving its public signature and behavior.",
            ["Zumbo.Modules.Projects|Zumbo.Modules.Projects.ProjectService|method:ListAsync:(stringorganizationId,CancellationTokenct,boolarchived=false):Task<IReadOnlyList<ProjectResponse>>"] =
                "The compatibility facade delegates project listing to the tenant-scoped ListProjects query slice while preserving its public signature.",
            ["Zumbo.Modules.Projects|Zumbo.Modules.Projects.CreateProjectHandler|method:HandleAsync:(CreateProjectRequestrequest,stringcorrelationId,CancellationTokenct):Task<ProjectResponse>"] =
                "The endpoint handler selects the independent project-creation slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Projects|Zumbo.Modules.Projects.ListProjectsHandler|method:HandleAsync:(ListProjectsQueryquery,CancellationTokenct):Task<IReadOnlyList<ProjectResponse>>"] =
                "The endpoint handler selects the independent project-list query slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Projects|Zumbo.Modules.Projects.ProjectService|ctor:(IDocumentRepository<ProjectDocument>projects,IProjectMemberDirectorymemberDirectory,IProjectTeamDirectoryteamDirectory,IProjectTeamUsageCheckerteamUsageChecker,IProjectAuditWriteraudit,IClockclock,ICurrentUsercurrentUser,IExpectedVersionAccessor?expectedVersions=null,IProjectOrganizationDirectory?organizationDirectory=null,IOptions<ProjectLifecycleOptions>?lifecycleOptions=null)"] =
                "The unchanged compatibility facade constructor now wires the port-focused create and list handlers from its existing dependencies; its public signature and all previous assignments remain intact.",
            ["Zumbo.Api|BoardsEndpoints|method:AddBoardsModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Board create and project-list handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Api|BoardsEndpoints|method:MapBoardsEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The board update route resolves the independent UpdateBoard handler while preserving its route, authorization, request, response, and correlation behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:CreateAsync:(CreateBoardRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates board creation to the port-focused CreateBoard slice while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:ListByProjectAsync:(stringprojectId,CancellationTokenct,boolarchived=false):Task<IReadOnlyList<BoardResponse>>"] =
                "The compatibility facade delegates board listing to the project-scoped ListBoardsByProject query slice while preserving its public signature.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:UpdateAsync:(stringboardId,UpdateBoardRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates board updates to the port-focused UpdateBoard handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:ArchiveAsync:(stringboardId,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates board archival to the port-focused ArchiveBoard handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:RestoreAsync:(stringboardId,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates board restoration to the port-focused RestoreBoard handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:UpdateSwimlaneAsync:(stringboardId,UpdateSwimlaneRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates swimlane updates to the port-focused UpdateSwimlane handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:AddColumnAsync:(stringboardId,CreateColumnRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates column creation to the port-focused AddColumn handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:UpdateColumnAsync:(stringboardId,stringcolumnId,UpdateColumnRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates column updates to the port-focused UpdateColumn handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:DeleteColumnAsync:(stringboardId,stringcolumnId,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates column deletion to the port-focused DeleteColumn handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:ReorderColumnsAsync:(stringboardId,ReorderColumnsRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates column ordering to the port-focused ReorderColumns handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:CreateViewAsync:(stringboardId,CreateBoardViewRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates saved-view creation to the port-focused CreateView handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:UpdateViewAsync:(stringboardId,stringviewId,UpdateBoardViewRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates saved-view updates to the port-focused UpdateView handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|method:DeleteViewAsync:(stringboardId,stringviewId,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The compatibility facade delegates saved-view deletion to the port-focused DeleteView handler while preserving its public signature and behavior.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.CreateBoardHandler|method:HandleAsync:(CreateBoardRequestrequest,stringcorrelationId,CancellationTokenct):Task<BoardResponse>"] =
                "The endpoint handler selects the independent board-creation slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.ListBoardsByProjectHandler|method:HandleAsync:(ListBoardsByProjectQueryquery,CancellationTokenct):Task<IReadOnlyList<BoardResponse>>"] =
                "The endpoint handler selects the independent project-board-list slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Boards|Zumbo.Modules.Boards.BoardService|ctor:(IDocumentRepository<BoardDocument>boards,IBoardProjectAccessCheckeraccessChecker,IBoardColumnUsageCheckerusageChecker,IDistributedLockProviderdistributedLockProvider,IOptions<DistributedLockOptions>distributedLockOptions,IClockclock,ICurrentUsercurrentUser,IBoardAuditWriteraudit,IExpectedVersionAccessor?expectedVersions=null,IBoardWorkflowCatalog?workflowCatalog=null)"] =
                "The unchanged compatibility facade constructor now wires the port-focused create and list handlers from its existing dependencies; its public signature and previous expected-version assignment remain intact.",
            ["Zumbo.Api|WorkflowEndpoints|method:AddWorkflowsModule:(thisIServiceCollectionservices,IConfiguration?configuration=null):IServiceCollection"] =
                "Workflow upsert and read handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.WorkflowService|method:UpsertAsync:(CreateWorkflowRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkflowResponse>"] =
                "The compatibility facade delegates workflow upsert to the port-focused UpsertWorkflow slice while preserving its public signature and behavior.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.WorkflowService|method:GetOrCreateDefaultAsync:(stringprojectId,CancellationTokenct):Task<WorkflowResponse>"] =
                "The compatibility facade delegates workflow retrieval and default creation to the project-scoped GetWorkflow slice while preserving its public signature.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.UpsertWorkflowHandler|method:HandleAsync:(CreateWorkflowRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkflowResponse>"] =
                "The endpoint handler selects the independent workflow-upsert slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.GetWorkflowHandler|method:HandleAsync:(GetWorkflowQueryquery,CancellationTokenct):Task<WorkflowResponse>"] =
                "The endpoint handler selects the independent workflow-read slice when composed from ports and retains its original facade constructor.",
            ["Zumbo.Modules.Workflows|Zumbo.Modules.Workflows.WorkflowService|ctor:(IDocumentRepository<WorkflowDefinitionDocument>workflows,IWorkflowProjectAccessCheckeraccessChecker,IDistributedLockProviderdistributedLockProvider,IOptions<DistributedLockOptions>distributedLockOptions,IClockclock,IWorkflowAuditWriteraudit,IExpectedVersionAccessor?expectedVersions=null,IWorkflowPublicationGuard?publicationGuard=null)"] =
                "The unchanged compatibility facade constructor now wires port-focused upsert and read handlers from its existing dependencies; its public signature and expected-version state remain intact.",
            ["Zumbo.Api|WorkItemEndpoints|method:AddWorkItemsModule:(thisIServiceCollectionservices,IConfiguration?configuration=null):IServiceCollection"] =
                "Work-item create, search, comment, relation-parent/link/unlink, attachment-open/upload/delete, due-date-reminder, report-project-summary/status-distribution/user-workload/due-date-risks/flow-time/completion-rate/team-performance, webhook subscription-create/list/read/state/update/secret-rotation, delivery-test/queue/dispatch/metrics/list/read/replay, development connection-create/list/read/disconnect/delete, connection-mapping create/list/delete and work-item discovery, work-item-link listing/creation/deletion, webhook reception/processing, credential-rotation, development-webhook-secret-rotation, provider-health, and repository-discovery handlers remain scoped; comment, relation, attachment, reminder and report factories retain their order through their WorkItems composition classes, the webhook delivery adapter selects QueueDeliveryHandler explicitly, and hosted and compatibility services remain registered.",
            ["Zumbo.Api|WebhookEndpoints|method:MapWebhookEndpoints:(thisRouteGroupBuilderapi):void"] =
                "The webhook subscription-create/list/read/state/update/secret-rotation and delivery test/metrics/list/read/replay routes resolve independent handlers while preserving routes, authorization, tenant management and ownership checks, secret handling and overlap, validation, immutable payload, not-found and conflict behavior, state, metric, paging and replay semantics, response mapping, and compatibility facades under the exact runtime contract audit.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.CreateWorkItemHandler|method:HandleAsync:(CreateWorkItemRequestrequest,stringcorrelationId,CancellationTokenct):Task<WorkItemResponse>"] =
                "The endpoint handler selects the independent work-item creation slice when composed from ports and retains its original WorkItemService constructor as a compatibility path.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.SearchWorkItemsHandler|method:HandleAsync:(WorkItemSearchRequestrequest,CancellationTokenct):Task<IReadOnlyList<WorkItemResponse>>"] =
                "The endpoint handler selects the independent work-item search slice when composed from ports and retains its original WorkItemService constructor as a compatibility path.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:CreateAsync:(CreateWorkItemRequestrequest,stringcorrelationId,CancellationTokenct,string?requestedId=null):Task<WorkItemResponse>"] =
                "The compatibility facade delegates ordinary and requested-id work-item creation to the same port-focused slice while preserving its public signature; the explicit intake contract and preserved private core member also delegate through the handler without retaining persistence logic.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:CreateCoreAsync:(CreateWorkItemRequestrequest,stringorganizationId,stringcorrelationId,CancellationTokenct,string?requestedId,stringactorUserId,string?intakeSubmissionId,IReadOnlyCollection<StoredAttachment>initialAttachments,stringdescription=\"\"):Task<WorkItemResponse>"] =
                "The preserved private compatibility member delegates its complete organization, requested identity, actor, intake metadata, attachment and description context to the port-focused creation slice; targeted tests preserve requested-ID and intake behavior while the member signature remains unchanged.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:IIntakeWorkItemCreator.CreateAsync:(IntakeWorkItemCreationcreation,CancellationTokenct):Task<WorkItemResponse>"] =
                "The explicit intake compatibility contract delegates to the creation handler; organization and submission validation, stable identity, conflict and idempotency behavior, activity hydration, source metadata, initial attachments and description now execute in the shared port-focused slice.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SearchAsync:(WorkItemSearchRequestrequest,CancellationTokenct):Task<IReadOnlyList<WorkItemResponse>>"] =
                "The compatibility facade delegates work-item search to the port-focused query slice while preserving the original public signature and tenant-scoped behavior.",
            ["Zumbo.Modules.WorkItems|Zumbo.Modules.WorkItems.WorkItemService|method:SearchPageAsync:(WorkItemSearchRequestrequest,CancellationTokenct):Task<WorkItemSearchPageResponse>"] =
                "The compatibility facade delegates paged work-item search to the existing port-focused query slice while preserving validation, view authorization, tenant scope, type-schema filtering, page bounds, indexed ordering, exact empty-result totals, repository fallback ordering and count, bounded degraded fallback, activity hydration, degraded-state reporting, cancellation, and the public signature.",
            ["Zumbo.Api|NotificationEndpoints|method:AddNotificationsModule:(thisIServiceCollectionservices,IConfigurationconfiguration):IServiceCollection"] =
                "Notification list and mark-read handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Notifications|Zumbo.Modules.Notifications.ListNotificationsHandler|method:HandleAsync:(ListNotificationsQueryquery,CancellationTokenct):Task<IReadOnlyList<NotificationResponse>>"] =
                "The endpoint handler selects the independent notification-list slice when composed from ports and retains its original NotificationService constructor as a compatibility path.",
            ["Zumbo.Modules.Notifications|Zumbo.Modules.Notifications.MarkNotificationAsReadHandler|method:HandleAsync:(MarkNotificationAsReadCommandcommand,CancellationTokenct):Task<MarkNotificationAsReadResponse>"] =
                "The endpoint handler selects the independent mark-read slice when composed from ports and retains its original NotificationService constructor as a compatibility path.",
            ["Zumbo.Modules.Notifications|Zumbo.Modules.Notifications.NotificationService|method:ListAsync:(stringuserId,CancellationTokenct,intpage=1,intpageSize=50,boolunreadOnly=false):Task<IReadOnlyList<NotificationResponse>>"] =
                "The compatibility facade delegates notification listing to the port-focused query slice while preserving its public signature, paging, ordering, and user isolation.",
            ["Zumbo.Modules.Notifications|Zumbo.Modules.Notifications.NotificationService|method:MarkAsReadAsync:(stringnotificationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates the idempotent mark-read mutation to its port-focused slice while preserving the original public signature and authorization behavior.",
            ["Zumbo.Api|AuditEndpoints|method:AddAuditModule:(thisIServiceCollectionservices):IServiceCollection"] =
                "Audit write and query handlers remain scoped while explicit factories select their port-focused constructors and preserve compatibility constructors.",
            ["Zumbo.Modules.Audit|Zumbo.Modules.Audit.WriteAuditLogHandler|method:HandleAsync:(WriteAuditLogCommandcommand,CancellationTokenct):Task<WriteAuditLogResponse>"] =
                "The endpoint handler validates the command and selects the independent audit-write slice when composed from ports while retaining its original AuditService constructor.",
            ["Zumbo.Modules.Audit|Zumbo.Modules.Audit.QueryAuditLogHandler|method:HandleAsync:(AuditLogQueryquery,CancellationTokenct):Task<AuditLogPageResponse>"] =
                "The endpoint handler selects the independent audit-query slice when composed from ports and retains its original AuditService constructor as a compatibility path.",
            ["Zumbo.Modules.Audit|Zumbo.Modules.Audit.AuditService|ctor:(IDocumentRepository<AuditLogDocument>auditLogs,IClockclock,ICurrentUsercurrentUser,IAuditRequestContextrequestContext,IAuditAccessCheckeraccessChecker,IOptions<AuditOptions>?options=null,IAuditTenantResolver?tenantResolver=null,IDistributedLockProvider?distributedLocks=null)"] =
                "The unchanged service constructor now wires port-focused write and query handlers from its existing dependencies while preserving every prior field assignment and optional dependency.",
            ["Zumbo.Modules.Audit|Zumbo.Modules.Audit.AuditService|method:WriteAsync:(stringaction,stringentityType,stringentityId,string?oldValue,string?newValue,stringcorrelationId,CancellationTokenct):Task"] =
                "The compatibility facade delegates ordinary audit writes through the unchecked handler path, preserving the original normalization behavior and public signature.",
            ["Zumbo.Modules.Audit|Zumbo.Modules.Audit.AuditService|method:QueryAsync:(AuditLogQueryquery,CancellationTokenct):Task<AuditLogPageResponse>"] =
                "The compatibility facade delegates audit paging to the port-focused query slice while preserving validation, authorization, filtering, ordering, and cursor behavior."
        };

    private static string ProjectDirectory => Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", ".."));

    private static string RepositoryDirectory => Directory.GetParent(ProjectDirectory)!.FullName;

    private static string ReportDirectory => Path.Combine(ProjectDirectory, "docs", "architecture");

    [Fact]
    public void RefactorSnapshot_PreservesBaselineSemanticInventoryAndNormalizedBodies()
    {
        var baseline = RefactorSemanticInventory.ReadGitSnapshot(
            RepositoryDirectory,
            RefactorSemanticInventory.BaselineCommit);
        var target = RefactorSemanticInventory.ReadWorkingTree(ProjectDirectory);
        var comparison = RefactorSemanticInventory.Compare(baseline, target);
        var reports = RefactorValidationReportBuilder.Build(comparison, AcceptedBodyDifferences);

        if (Environment.GetEnvironmentVariable("ZUMBO_UPDATE_REFACTOR_REPORTS") == "1")
        {
            Directory.CreateDirectory(ReportDirectory);
            foreach (var (fileName, content) in reports)
            {
                File.WriteAllText(Path.Combine(ReportDirectory, fileName), content);
            }
        }

        foreach (var (fileName, expected) in reports)
        {
            var path = Path.Combine(ReportDirectory, fileName);
            Assert.True(File.Exists(path), $"Missing generated refactor validation report: {fileName}");
            Assert.Equal(expected, File.ReadAllText(path).Replace("\r\n", "\n", StringComparison.Ordinal));
        }

        Assert.Empty(comparison.MissingTypes);
        Assert.Empty(comparison.TypeSignatureDifferences);
        Assert.Empty(comparison.MissingMembers);
        Assert.Empty(comparison.MemberSignatureDifferences);

        var unexplainedBodyDifferences = comparison.BodyDifferences
            .Where(item => !AcceptedBodyDifferences.ContainsKey(item.Id))
            .Select(item => item.Id)
            .ToArray();
        Assert.Empty(unexplainedBodyDifferences);
    }
}
