import { CommonModule } from '@angular/common';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { IonContent, IonHeader, IonRefresher, IonRefresherContent, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { ZumboSessionService, normalizeApiError } from '@zumbo/modern-shared';
import { finalize } from 'rxjs';
import { MobileConnectivityService } from '../../shell/mobile-connectivity.service';
import { compatibleMobileProjectIntakeFields, editMobileProjectIntakeDraft, hasMobileProjectIntakePermission, mobileProjectIntakeAccessLabel, mobileProjectIntakeErrorMessage, mobileProjectIntakeFieldTypes, mobileProjectIntakeLimits, mobileProjectIntakeSecurityLabel, mobileProjectIntakeStateLabel, mobileProjectIntakeSubmissionData, mobileProjectIntakeSubmissionValue, mobileProjectIntakeTriageStates, newMobileProjectIntakeDraft, newMobileProjectIntakeField, newMobileProjectIntakeSubmission, validateMobileProjectIntakeDraft, validateMobileProjectIntakeSubmission } from './mobile-project-intake.core';
import { MobileProjectIntakeDraft, MobileProjectIntakeField, MobileProjectIntakeFieldDraft, MobileProjectIntakeForm, MobileProjectIntakeSubmission, MobileProjectIntakeTab } from './mobile-project-intake.models';
import { MobileProjectIntakeService } from './mobile-project-intake.service';

@Component({ selector: 'zumbo-mobile-project-intake', imports: [CommonModule, FormsModule, IonContent, IonHeader, IonRefresher, IonRefresherContent, IonTitle, IonToolbar], providers: [MobileProjectIntakeService], templateUrl: './mobile-project-intake.page.html', styleUrls: ['./mobile-project-intake.page.scss', './mobile-project-intake-responsive.scss'] })
export class MobileProjectIntakePage {
  private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly destroyRef = inject(DestroyRef); private readonly api = inject(MobileProjectIntakeService); private readonly session = inject(ZumboSessionService);
  protected readonly connectivity = inject(MobileConnectivityService);
  private readonly projectId = this.route.snapshot.paramMap.get('projectId') ?? '';
  protected readonly loading = signal(true); protected readonly refreshing = signal(false); protected readonly busy = signal(false); protected readonly queueLoading = signal(false); protected readonly error = signal<string | null>(null); protected readonly notice = signal<string | null>(null);
  protected readonly tab = signal<MobileProjectIntakeTab>(this.asTab(this.route.snapshot.queryParamMap.get('tab'))); protected readonly project = signal<import('./mobile-project-intake.models').MobileProjectIntakeProject | null>(null); protected readonly boards = signal<readonly import('./mobile-project-intake.models').MobileProjectIntakeBoard[]>([]); protected readonly roles = signal<readonly import('./mobile-project-intake.models').MobileProjectIntakeRole[]>([]); protected readonly schema = signal<import('./mobile-project-intake.models').MobileProjectIntakeSchema | null>(null); protected readonly forms = signal<readonly MobileProjectIntakeForm[]>([]); protected readonly selectedFormId = signal(''); protected readonly draft = signal<MobileProjectIntakeDraft | null>(null); protected readonly published = signal<import('./mobile-project-intake.models').MobileProjectIntakePublishedForm | null>(null); protected readonly submission = signal<import('./mobile-project-intake.models').MobileProjectIntakeSubmissionModel | null>(null); protected readonly confirmation = signal<import('./mobile-project-intake.models').MobileProjectIntakeConfirmation | null>(null); protected readonly queue = signal<readonly MobileProjectIntakeSubmission[]>([]); protected readonly queueTotal = signal(0); protected readonly queueState = signal(''); protected readonly triageNotes = signal<Record<string, string>>({});
  protected readonly limits = mobileProjectIntakeLimits; protected readonly fieldTypes = mobileProjectIntakeFieldTypes; protected readonly triageStates = mobileProjectIntakeTriageStates;
  protected readonly selectedForm = computed(() => this.forms().find(form => form.id === this.selectedFormId()) ?? null); protected readonly internalForms = computed(() => this.forms().filter(form => form.state === 'Published' && form.draft.accessPolicy === 'Internal')); protected readonly roleName = computed(() => this.project()?.members?.find(member => member.userId === this.session.currentUser()?.id)?.role ?? null); protected readonly canManage = computed(() => hasMobileProjectIntakePermission(this.roleName(), this.roles(), 'WorkflowManage')); protected readonly canSubmit = computed(() => hasMobileProjectIntakePermission(this.roleName(), this.roles(), 'WorkItemCreate')); protected readonly canTriage = computed(() => hasMobileProjectIntakePermission(this.roleName(), this.roles(), 'WorkItemUpdate')); protected readonly issueTypes = computed(() => [...(this.schema()?.issueTypes ?? [])].filter(item => item.active !== false).sort((left, right) => left.position - right.position)); protected readonly customFields = computed(() => [...(this.schema()?.customFields ?? [])].filter(item => item.active !== false).sort((left, right) => left.position - right.position)); protected readonly draftError = computed(() => validateMobileProjectIntakeDraft(this.draft())); protected readonly submissionError = computed(() => validateMobileProjectIntakeSubmission(this.published(), this.submission()));
  constructor() { this.load(); }
  protected refresh(event: Event): void { const refresher = event.target as HTMLIonRefresherElement; if (this.connectivity.offline()) { this.notice.set('Çevrimdışıyken yenileme yapılamaz.'); void refresher.complete(); return; } this.refreshing.set(true); this.load(() => { this.refreshing.set(false); void refresher.complete(); }); }
  protected load(done?: () => void): void { if (!this.projectId) { this.loading.set(false); this.error.set('Proje bağlantısı geçersiz.'); done?.(); return; } if (!this.refreshing()) this.loading.set(true); this.error.set(null); this.api.load(this.projectId).pipe(finalize(() => { this.loading.set(false); done?.(); }), takeUntilDestroyed(this.destroyRef)).subscribe({ next: context => { this.project.set(context.project); this.boards.set(context.boards); this.roles.set(context.roles); this.schema.set(context.schema); this.forms.set(context.forms); const selected = context.forms.find(form => form.id === this.selectedFormId()) ?? context.forms.find(form => form.state !== 'Archived') ?? context.forms[0]; if (selected) this.selectForm(selected, true); else this.draft.set(null); if (this.tab() === 'submit') this.selectSubmissionForm(this.internalForms()[0]); if (this.tab() === 'triage') this.loadQueue(); }, error: value => this.error.set(this.message(value, 'Intake merkezi yüklenemedi.')) }); }
  protected setTab(tab: MobileProjectIntakeTab): void { this.tab.set(tab); this.clearFeedback(); void this.router.navigate([], { relativeTo: this.route, queryParams: { tab }, replaceUrl: true }); if (tab === 'submit') this.selectSubmissionForm(this.internalForms()[0]); if (tab === 'triage') this.loadQueue(); }
  protected newForm(): void { const project = this.project(); if (!project || !this.canManage() || !this.boards().length || this.connectivity.offline()) return; this.selectedFormId.set(''); this.draft.set(newMobileProjectIntakeDraft(project, this.boards(), this.issueTypes().find(item => item.key === 'Task')?.key ?? this.issueTypes()[0]?.key ?? '')); this.clearFeedback(); }
  protected selectForm(form: MobileProjectIntakeForm, preserveTab = false): void { this.selectedFormId.set(form.id); this.draft.set(editMobileProjectIntakeDraft(form)); if (!preserveTab) this.tab.set('forms'); }
  protected addField(): void { this.draft.update(draft => draft && draft.definition.fields.length < this.limits.fields ? { ...draft, definition: { ...draft.definition, fields: [...draft.definition.fields, newMobileProjectIntakeField(draft.definition.fields.length)] } } : draft); }
  protected removeField(index: number): void { this.draft.update(draft => { if (!draft || draft.definition.fields.length <= 1) return draft; const removed = draft.definition.fields[index]; const mapping = draft.definition.mapping; return { ...draft, definition: { ...draft.definition, fields: draft.definition.fields.filter((_, itemIndex) => itemIndex !== index), mapping: { ...mapping, titleFieldKey: mapping.titleFieldKey === removed.key ? '' : mapping.titleFieldKey, descriptionFieldKey: mapping.descriptionFieldKey === removed.key ? '' : mapping.descriptionFieldKey, priorityFieldKey: mapping.priorityFieldKey === removed.key ? '' : mapping.priorityFieldKey, dueDateFieldKey: mapping.dueDateFieldKey === removed.key ? '' : mapping.dueDateFieldKey, customFields: mapping.customFields.filter(item => item.intakeFieldKey !== removed.key) } } }; }); }
  protected updateField(index: number, field: keyof MobileProjectIntakeFieldDraft, event: Event): void { const target = event.target as HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement; const value = field === 'required' ? (target as HTMLInputElement).checked : target.value; this.draft.update(draft => draft ? { ...draft, definition: { ...draft.definition, fields: draft.definition.fields.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item) } } : draft); }
  protected compatibleFields(target: 'title' | 'description' | 'priority' | 'dueDate' | 'custom'): readonly MobileProjectIntakeFieldDraft[] { return compatibleMobileProjectIntakeFields(this.draft()?.definition.fields ?? [], target); }
  protected addCustomMapping(): void { this.draft.update(draft => draft ? { ...draft, definition: { ...draft.definition, mapping: { ...draft.definition.mapping, customFields: [...draft.definition.mapping.customFields, { intakeFieldKey: '', workItemFieldKey: '' }] } } } : draft); }
  protected removeCustomMapping(index: number): void { this.draft.update(draft => draft ? { ...draft, definition: { ...draft.definition, mapping: { ...draft.definition.mapping, customFields: draft.definition.mapping.customFields.filter((_, itemIndex) => itemIndex !== index) } } } : draft); }
  protected saveForm(): void { const draft = this.draft(); if (!draft || !this.canManage() || this.connectivity.offline() || this.busy() || this.draftError()) return; this.busy.set(true); this.clearFeedback(); this.api.save(draft).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: form => { this.upsert(form); this.selectForm(form, true); this.notice.set(draft.id ? 'Form taslağı güncellendi.' : 'Form taslağı oluşturuldu.'); }, error: value => { this.error.set(this.message(value, 'Form kaydedilemedi.')); if (normalizeApiError(value).code === 'CONCURRENCY_CONFLICT') this.load(); } }); }
  protected publishForm(form: MobileProjectIntakeForm): void { this.mutate(this.api.publish(form.id), 'Formun yeni sürümü yayınlandı.'); }
  protected archiveForm(form: MobileProjectIntakeForm): void { this.mutate(this.api.archive(form.id), 'Form arşivlendi.'); }
  protected selectSubmissionForm(form?: MobileProjectIntakeForm): void { if (!form || !this.canSubmit()) { this.published.set(null); this.submission.set(null); return; } this.selectedFormId.set(form.id); this.busy.set(true); this.clearFeedback(); this.api.published(form.id).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: value => { this.published.set(value); this.submission.set(newMobileProjectIntakeSubmission(value)); this.confirmation.set(null); }, error: value => this.error.set(this.message(value, 'Yayındaki form yüklenemedi.')) }); }
  protected captureFiles(field: MobileProjectIntakeField, event: Event): void { if (this.connectivity.offline()) return; const files = Array.from((event.target as HTMLInputElement).files ?? []); this.submission.update(model => model ? { ...model, files: { ...model.files, [field.key]: files } } : model); }
  protected submitRequest(): void { const form = this.published(), model = this.submission(), selected = this.selectedForm(); if (!form || !model || !selected || !this.canSubmit() || this.connectivity.offline() || this.busy() || this.submissionError()) return; this.busy.set(true); this.clearFeedback(); this.api.submit(selected.id, mobileProjectIntakeSubmissionData(form, model)).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: value => { this.confirmation.set(value); this.submission.set(newMobileProjectIntakeSubmission(form)); }, error: value => this.error.set(this.message(value, 'Talep gönderilemedi.')) }); }
  protected loadQueue(): void { const form = this.selectedForm() ?? this.forms()[0]; if (!form) { this.queue.set([]); this.queueTotal.set(0); return; } this.selectedFormId.set(form.id); this.queueLoading.set(true); this.error.set(null); this.api.queue(form.id, this.queueState()).pipe(finalize(() => this.queueLoading.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: page => { this.queue.set(page.items); this.queueTotal.set(page.totalCount); }, error: value => this.error.set(this.message(value, 'Triage kuyruğu yüklenemedi.')) }); }
  protected triage(item: MobileProjectIntakeSubmission, state: string): void { const form = this.selectedForm(); if (!form || !this.canTriage() || this.connectivity.offline() || this.busy() || item.state === 'Processing') return; this.busy.set(true); this.clearFeedback(); this.api.triage(form.id, item.id, state, this.triageNotes()[item.id] ?? '').pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: updated => { this.queue.update(items => items.map(item => item.id === updated.id ? updated : item)); this.notice.set('Talep durumu güncellendi.'); }, error: value => { this.error.set(this.message(value, 'Talep sınıflandırılamadı.')); if (normalizeApiError(value).code === 'CONCURRENCY_CONFLICT') this.loadQueue(); } }); }
  protected updateTriageNote(id: string, event: Event): void { this.triageNotes.update(notes => ({ ...notes, [id]: (event.target as HTMLTextAreaElement).value })); }
  protected openWorkItem(id?: string | null): void { if (id) void this.router.navigate(['/tasks', id]); }
  protected stateLabel(value: string): string { return mobileProjectIntakeStateLabel(value); } protected accessLabel(value: string): string { return mobileProjectIntakeAccessLabel(value); } protected securityLabel(value: string): string { return mobileProjectIntakeSecurityLabel(value); } protected submissionTitle(item: MobileProjectIntakeSubmission): string { return mobileProjectIntakeSubmissionValue(item, this.selectedForm()?.draft.mapping.titleFieldKey ?? '') || item.confirmationCode; }
  private mutate(request: ReturnType<MobileProjectIntakeService['publish']>, notice: string): void { if (!this.canManage() || this.connectivity.offline() || this.busy()) return; this.busy.set(true); this.clearFeedback(); request.pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: form => { this.upsert(form); this.selectForm(form, true); this.notice.set(notice); }, error: value => { this.error.set(this.message(value, 'Form işlemi tamamlanamadı.')); if (normalizeApiError(value).code === 'CONCURRENCY_CONFLICT') this.load(); } }); }
  private upsert(form: MobileProjectIntakeForm): void { this.forms.update(forms => forms.some(item => item.id === form.id) ? forms.map(item => item.id === form.id ? form : item) : [form, ...forms]); }
  private clearFeedback(): void { this.error.set(null); this.notice.set(null); }
  private message(value: unknown, fallback: string): string { return mobileProjectIntakeErrorMessage(normalizeApiError(value).code, fallback); }
  private asTab(value: string | null): MobileProjectIntakeTab { return value === 'submit' || value === 'triage' ? value : 'forms'; }
}
