import { BulkJob, ImportRow, JobRole, JobState, ParsedImport } from './jobs.models';

export const jobLimits = Object.freeze({ maxInputItems: 5000, maxInputBytes: 5 * 1024 * 1024, maxTitleLength: 200 });
const terminalStates = ['Completed', 'CompletedWithErrors', 'Cancelled'];

export function hasJobPermission(roleName: string | null, roles: readonly JobRole[], permission: string): boolean { const role = roles.find(item => item.name === roleName && item.isActive); return !!role?.permissions.some(item => item === '*' || item === permission); }
export function parseImport(text: string, byteLength: number): ParsedImport { if (byteLength > jobLimits.maxInputBytes) return invalid('Dosya 5 MB sınırını aşıyor.'); let source: unknown; try { source = JSON.parse(text); } catch { return invalid('Dosya geçerli JSON içermiyor.'); } const values = Array.isArray(source) ? source : source && typeof source === 'object' && Array.isArray((source as { items?: unknown }).items) ? (source as { items: unknown[] }).items : null; if (!values) return invalid('JSON kökünde bir satır dizisi veya items dizisi bulunmalı.'); if (!values.length || values.length > jobLimits.maxInputItems) return invalid('Dosya 1 ile 5000 satır arasında olmalı.'); const keys = new Set<string>(); const rows: ImportRow[] = []; const errors: string[] = []; values.forEach((value, index) => { if (!value || typeof value !== 'object' || Array.isArray(value)) { errors.push(`${index + 1}. satır bir nesne olmalı.`); return; } const item = value as Record<string, unknown>; const row: ImportRow = { sourceKey: stringValue(item['sourceKey']), boardId: stringValue(item['boardId']), title: stringValue(item['title']), type: stringValue(item['type']) || 'Task', priority: stringValue(item['priority']) || 'Medium', assigneeUserId: optional(item['assigneeUserId']), dueDate: optional(item['dueDate']), parentId: optional(item['parentId']), teamId: optional(item['teamId']), customFields: Array.isArray(item['customFields']) ? item['customFields'] : [] }; if (!row.sourceKey || !row.boardId || !row.title) errors.push(`${index + 1}. satırda sourceKey, boardId ve title zorunlu.`); else if (row.title.length > jobLimits.maxTitleLength) errors.push(`${index + 1}. satır başlığı 200 karakteri aşıyor.`); else if (keys.has(row.sourceKey)) errors.push(`${index + 1}. satırda yinelenen sourceKey: ${row.sourceKey}`); else { keys.add(row.sourceKey); rows.push(row); } }); return { valid: errors.length === 0, rows, errors: errors.slice(0, 20), totalErrors: errors.length }; }
export function isTerminal(job: BulkJob): boolean { return terminalStates.includes(job.state); }
export function canCancel(job: BulkJob): boolean { return !isTerminal(job) && job.state !== 'Failed' && !job.cancelRequested; }
export function canRetry(job: BulkJob): boolean { return ['Failed', 'CompletedWithErrors'].includes(job.state); }
export function artifactsExpired(job: BulkJob, now = Date.now()): boolean { const expires = Date.parse(job.artifactsExpireAt ?? ''); return Number.isFinite(expires) && expires <= now; }
export function progress(job: BulkJob): number { const total = Math.max(0, job.totalItems || 0); const processed = Math.min(total, Math.max(0, job.processedItems || 0)); return total ? Math.round(processed * 100 / total) : isTerminal(job) ? 100 : 0; }
export function jobState(job: BulkJob): JobState { if (artifactsExpired(job)) return { label: 'Dosyaların süresi doldu', tone: 'muted' }; return ({ Pending: { label: 'Sırada', tone: 'neutral' }, Running: { label: job.cancelRequested ? 'İptal bekleniyor' : 'Çalışıyor', tone: 'info' }, Completed: { label: job.dryRun ? 'Önizleme tamamlandı' : 'Tamamlandı', tone: 'success' }, CompletedWithErrors: { label: 'Kısmen tamamlandı', tone: 'warning' }, Cancelled: { label: 'İptal edildi', tone: 'muted' }, Failed: { label: 'Başarısız', tone: 'danger' } } as Record<string, JobState>)[job.state] ?? { label: job.state || 'Bilinmiyor', tone: 'neutral' }; }
export function jobType(job: BulkJob): string { if (job.type === 'Import') return job.dryRun ? 'İçe aktarım önizlemesi' : 'İçe aktarım'; if (job.type === 'Export') return job.dryRun ? 'Dışa aktarım önizlemesi' : 'Dışa aktarım'; return ({ Move: 'Durum değişikliği', Assign: 'Atama', Archive: 'Arşivleme' } as Record<string, string>)[job.operation ?? ''] ?? 'Toplu işlem'; }
function stringValue(value: unknown): string { return value == null ? '' : String(value).trim(); }
function optional(value: unknown): string | null { return stringValue(value) || null; }
function invalid(message: string): ParsedImport { return { valid: false, rows: [], errors: [message], totalErrors: 1 }; }
