<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zumbo.SharedKernel\Zumbo.SharedKernel.csproj" />
    <ProjectReference Include="..\Zumbo.BuildingBlocks.Infrastructure\Zumbo.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\Zumbo.Modules.Notifications\Zumbo.Modules.Notifications.csproj" />
    <ProjectReference Include="..\Zumbo.Modules.Audit\Zumbo.Modules.Audit.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
