import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {IonBackButton,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonSegment,IonSegmentButton,IonTitle,IonToolbar} from '@ionic/angular/standalone';
import {finalize} from 'rxjs';
import {normalizeApiError,ZumboSessionService} from '@zumbo/modern-shared';
import {MobileConnectivityService} from '../../shell/mobile-connectivity.service';
import {KnowledgeComment,KnowledgeContext,KnowledgeDocument,KnowledgeDraft,KnowledgePortfolio,KnowledgeRole,KnowledgeScope,KnowledgeSummary} from './mobile-knowledge.models';
import {MobileWorkspaceStore} from '../../shell/mobile-workspace.store';
import {MobileKnowledgeService} from './mobile-knowledge.service';
@Component({selector:'zumbo-mobile-knowledge',imports:[FormsModule,IonBackButton,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonSegment,IonSegmentButton,IonTitle,IonToolbar],providers:[MobileKnowledgeService],templateUrl:'./mobile-knowledge.page.html',styleUrls:['../strategy/mobile-strategy.page.scss','../strategy/mobile-strategy-detail.scss','./mobile-knowledge.page.scss','./mobile-knowledge-edit.scss']})
export class MobileKnowledgePage {
 private readonly api=inject(MobileKnowledgeService);private readonly session=inject(ZumboSessionService);private readonly store=inject(MobileWorkspaceStore);protected readonly connectivity=inject(MobileConnectivityService);protected readonly items=signal<readonly KnowledgeSummary[]>([]);protected readonly portfolios=signal<readonly KnowledgePortfolio[]>([]);protected readonly roles=signal<readonly KnowledgeRole[]>([]);protected readonly context=signal<KnowledgeContext|null>(null);protected readonly loading=signal(true);protected readonly busy=signal(false);protected readonly error=signal<string|null>(null);protected readonly selectedId=computed(()=>this.context()?.document.id||'');protected readonly tab=signal<'content'|'history'|'links'|'comments'|'edit'>('content');protected readonly scopes=computed(()=>this.buildScopes());protected query='';protected commentBody='';protected draft:KnowledgeDraft={scopeKey:'',title:'',contentMarkdown:'',tagsText:'',changeSummary:''};
 constructor(){this.load();}
 protected load(done?:()=>void){this.loading.set(true);this.error.set(null);this.api.list(this.query).pipe(finalize(()=>{this.loading.set(false);done?.();})).subscribe({next:value=>{this.items.set(value.documents.items.filter(item=>!item.archived));this.portfolios.set(value.portfolios.items);this.roles.set(value.roles);const id=this.selectedId()||this.items()[0]?.id;if(id)this.select(id);},error:()=>this.error.set('Bilgi dokümanları yüklenemedi.')});}
 protected select(id:string){this.api.detail(id).subscribe({next:document=>this.api.context(document).subscribe({next:value=>{this.context.set(value);this.tab.set('content');},error:()=>this.error.set('Doküman bağlantıları yüklenemedi.')}),error:()=>this.error.set('Doküman yüklenemedi.')});}
 protected refresh(event:Event){this.load(()=>void(event.target as unknown as{complete():Promise<void>}).complete());}
 protected search(){this.context.set(null);this.load();}
 protected addComment(){const context=this.context(),body=this.commentBody.trim();if(!context?.document.canComment||!body||this.busy()||this.connectivity.offline())return;this.busy.set(true);this.api.comment(context.document,body).pipe(finalize(()=>this.busy.set(false))).subscribe({next:document=>{this.context.set({...context,document});this.commentBody='';},error:value=>this.error.set(normalizeApiError(value).message||'Yorum eklenemedi.')});}
 protected canResolve(comment:KnowledgeComment){const document=this.context()?.document;return!!document&&!comment.resolved&&(document.canEdit||comment.authorUserId===this.session.currentUser()?.id);}
 protected resolve(comment:KnowledgeComment){const context=this.context();if(!context||!this.canResolve(comment)||this.busy()||this.connectivity.offline())return;this.busy.set(true);this.api.resolve(context.document,comment.id).pipe(finalize(()=>this.busy.set(false))).subscribe({next:document=>this.context.set({...context,document}),error:value=>this.error.set(normalizeApiError(value).message||'Yorum çözülemedi.')});}
 protected linked(ids:readonly string[],type:'workItems'|'users'){const options=this.context()?.links[type]||[];return ids.map(id=>options.find(item=>item.id===id)?.label||'Erişilemeyen kayıt');}
 protected date(value:string){return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(value));}
 protected edit(){const document=this.context()?.document;if(!document?.canEdit)return;this.draft=this.toDraft(document);this.tab.set('edit');}
 protected create(){const scope=this.scopes()[0];if(!scope)return;this.context.set(null);this.draft={scopeKey:scope.key,title:'',contentMarkdown:'',tagsText:'',changeSummary:''};this.tab.set('edit');}
 protected cancel(){const document=this.context()?.document;if(document)this.tab.set('content');else this.load();}
 protected save(){const scope=this.scopes().find(item=>item.key===this.draft.scopeKey),document=this.context()?.document;if(!scope||!this.draft.title.trim()||!this.draft.changeSummary.trim()||this.busy()||this.connectivity.offline()||(document&&!document.canEdit))return;this.busy.set(true);this.api.save(this.draft,scope,document).pipe(finalize(()=>this.busy.set(false))).subscribe({next:value=>{this.context.set(null);this.query='';this.load();this.select(value.id);},error:value=>this.error.set(normalizeApiError(value).message||'Doküman kaydedilemedi.')});}
 protected archive(){const document=this.context()?.document;if(!document?.canEdit||this.busy()||this.connectivity.offline()||!confirm('Bu dokümanı arşivlemek istiyor musunuz?'))return;this.busy.set(true);this.api.archive(document).pipe(finalize(()=>this.busy.set(false))).subscribe({next:()=>{this.context.set(null);this.load();},error:value=>this.error.set(normalizeApiError(value).message||'Doküman arşivlenemedi.')});}
 private toDraft(document:KnowledgeDocument):KnowledgeDraft{return{id:document.id,scopeKey:`${document.scopeType}:${document.scopeId}`,title:document.title,contentMarkdown:document.contentMarkdown,tagsText:document.tags.join(', '),changeSummary:'',version:document.version};}
 private buildScopes():KnowledgeScope[]{const user=this.session.currentUser();if(!user)return[];const result:KnowledgeScope[]=[];for(const project of this.store.projects()){const roleName=project.members?.find(member=>member.userId===user.id)?.role,role=this.roles().find(item=>item.isActive&&item.name===roleName);if(role?.permissions.some(value=>value==='*'||value==='BoardManage'))result.push({key:`Project:${project.id}`,type:'Project',id:project.id,label:`${project.key} · ${project.name}`});}for(const portfolio of this.portfolios())for(const initiative of portfolio.initiatives)if(portfolio.canEdit||initiative.canUpdateStatus||initiative.ownerUserId===user.id)result.push({key:`Initiative:${initiative.id}`,type:'Initiative',id:initiative.id,label:`${portfolio.name} · ${initiative.name}`});return result;}
}
