import { MobileDashboardRenderedWidget, MobileRawReport, MobileReportSnapshot, MobileReportingData, MobileReportingRole } from './mobile-reporting.models';

export function mobileReportSnapshot<T>(response: MobileRawReport<T>): MobileReportSnapshot<T> {
  return { data: response.body?.data as T, generatedAt: response.headers.get('X-Zumbo-Report-Generated-At'), sourceVersion: finite(response.headers.get('X-Zumbo-Report-Source-Version')), stale: response.headers.get('X-Zumbo-Report-Stale')?.toLowerCase() === 'true', ageSeconds: finite(response.headers.get('X-Zumbo-Report-Age-Seconds')) };
}
export function hasMobileReportingPermission(roleName: string | null, roles: readonly MobileReportingRole[], permission: string): boolean { const role = roles.find(item => item.isActive && item.name === roleName); return !!role && (role.permissions.includes('*') || role.permissions.includes(permission)); }
export function mobileReportingFreshness(data: MobileReportingData): { readonly generatedAt: string | null; readonly stale: boolean; readonly ageSeconds: number } { const values = Object.values(data.snapshots); const generated = values.map(value => Date.parse(value.generatedAt ?? '')).filter(Number.isFinite); return { generatedAt: generated.length ? new Date(Math.min(...generated)).toISOString() : null, stale: values.some(value => value.stale), ageSeconds: Math.max(0, ...values.map(value => value.ageSeconds)) }; }
export function mobileStatusRows(data: MobileReportingData): readonly { readonly key: string; readonly label: string; readonly count: number; readonly percent: number }[] { const total = data.snapshots.status.data.reduce((sum, row) => sum + row.count, 0); return data.snapshots.status.data.map(row => ({ key: row.status, label: mobileWorkflowLabel(data, row.status), count: row.count, percent: total ? Math.round(row.count / total * 100) : 0 })); }
export function mobileWorkflowLabel(data: MobileReportingData, key: string): string { return data.workflow.statuses.find(item => item.key === key)?.name ?? key; }
export function mobileReportDays(hours?: number | null): string { return hours == null ? 'Veri yok' : `${(hours / 24).toLocaleString('tr-TR', { maximumFractionDigits: 1 })} gün`; }
export function mobileDashboardState(widget: MobileDashboardRenderedWidget): string { return widget.status === 'Ready' ? 'Hazır' : widget.status === 'Stale' ? 'Eski veri' : 'Kısmi'; }
export function mobileDashboardTypeLabel(type: string): string { return ({ ProjectSummary: 'Proje özeti', StatusDistribution: 'Durum dağılımı', UserWorkload: 'İş yükü', DueDateRisks: 'Teslimat riskleri', FlowTime: 'Akış süresi', CompletionRate: 'Tamamlama oranı', TeamPerformance: 'Ekip teslimatı' } as Readonly<Record<string, string>>)[type] ?? 'Rapor bileşeni'; }
export function mobileDashboardCell(row: Readonly<Record<string, string | null>>, key: string): string { const value = row[key]; return value == null || value === '' ? '—' : String(value); }
function finite(value: unknown): number { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; }
