import { CommonModule, DOCUMENT } from '@angular/common';
import { Component, DestroyRef, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { IonContent, IonHeader, IonRefresher, IonRefresherContent, IonTitle, IonToolbar } from '@ionic/angular/standalone';
import { ZumboSessionService, normalizeApiError } from '@zumbo/modern-shared';
import { finalize } from 'rxjs';
import { MobileConnectivityService } from '../../shell/mobile-connectivity.service';
import { MobileWorkspaceStore } from '../../shell/mobile-workspace.store';
import { hasMobileReportingPermission, mobileDashboardCell, mobileDashboardState, mobileDashboardTypeLabel, mobileReportDays, mobileReportingFreshness, mobileStatusRows, mobileWorkflowLabel } from './mobile-reporting.core';
import { MobileDashboard, MobileDashboardRender, MobileReportingData, MobileReportingTab } from './mobile-reporting.models';
import { MobileReportingService } from './mobile-reporting.service';

@Component({ selector: 'zumbo-mobile-reporting', imports: [CommonModule, RouterLink, IonContent, IonHeader, IonRefresher, IonRefresherContent, IonTitle, IonToolbar], providers: [MobileReportingService], templateUrl: './mobile-reporting.page.html', styleUrls: ['./mobile-reporting.page.scss', './mobile-reporting-responsive.scss'] })
export class MobileReportingPage {
  private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly api = inject(MobileReportingService); private readonly session = inject(ZumboSessionService); private readonly destroyRef = inject(DestroyRef); private readonly document = inject(DOCUMENT);
  protected readonly connectivity = inject(MobileConnectivityService); protected readonly workspace = inject(MobileWorkspaceStore);
  private readonly projectId = this.route.snapshot.paramMap.get('projectId') ?? '';
  protected readonly tab = signal<MobileReportingTab>(this.initialTab()); protected readonly rangeDays = signal<30 | 90 | 180>(this.initialRange()); protected readonly loading = signal(true); protected readonly busy = signal(false); protected readonly error = signal<string | null>(null); protected readonly notice = signal<string | null>(null); protected readonly data = signal<MobileReportingData | null>(null); protected readonly dashboards = signal<readonly MobileDashboard[]>([]); protected readonly selectedDashboardId = signal(''); protected readonly render = signal<MobileDashboardRender | null>(null);
  protected readonly project = computed(() => this.data()?.project ?? null); protected readonly selectedDashboard = computed(() => this.dashboards().find(item => item.id === this.selectedDashboardId()) ?? null); protected readonly roleName = computed(() => this.project()?.members?.find(member => member.userId === this.session.currentUser()?.id)?.role ?? null); protected readonly canView = computed(() => hasMobileReportingPermission(this.roleName(), this.data()?.roles ?? [], 'WorkItemView')); protected readonly freshness = computed(() => this.data() ? mobileReportingFreshness(this.data()!) : null); protected readonly statusRows = computed(() => this.data() ? mobileStatusRows(this.data()!) : []);
  constructor() { this.load(); }
  protected load(done?: () => void): void { if (!this.projectId) { this.loading.set(false); this.error.set('Proje bağlantısı geçersiz.'); done?.(); return; } this.loading.set(true); this.error.set(null); this.api.load(this.projectId, this.rangeDays()).pipe(finalize(() => { this.loading.set(false); done?.(); }), takeUntilDestroyed(this.destroyRef)).subscribe({ next: data => { this.data.set(data); if (this.tab() === 'dashboards') this.loadDashboards(); }, error: value => this.error.set(normalizeApiError(value).message || 'Proje içgörüleri yüklenemedi.') }); }
  protected refresh(event: Event): void { const refresher = event.target as HTMLIonRefresherElement; if (this.connectivity.offline()) { this.notice.set('Çevrimdışıyken raporlar yenilenemez.'); void refresher.complete(); return; } this.load(() => void refresher.complete()); }
  protected setTab(tab: MobileReportingTab): void { this.tab.set(tab); this.error.set(null); this.notice.set(null); void this.router.navigate([], { relativeTo: this.route, queryParams: { mode: tab, range: this.rangeDays() }, replaceUrl: true }); if (tab === 'dashboards' && !this.dashboards().length) this.loadDashboards(); }
  protected changeRange(event: Event): void { this.rangeDays.set(Number((event.target as HTMLSelectElement).value) as 30 | 90 | 180); void this.router.navigate([], { relativeTo: this.route, queryParams: { mode: this.tab(), range: this.rangeDays() }, replaceUrl: true }); this.load(); }
  protected loadDashboards(): void { if (this.connectivity.offline()) { this.notice.set('Çevrimdışıyken dashboardlar yenilenemez.'); return; } this.busy.set(true); this.api.dashboards(this.projectId).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: items => { this.dashboards.set(items); const selected = items.find(item => item.id === this.selectedDashboardId()) ?? items[0]; if (selected) this.selectDashboard(selected); else { this.selectedDashboardId.set(''); this.render.set(null); } }, error: value => this.error.set(normalizeApiError(value).message || 'Dashboardlar yüklenemedi.') }); }
  protected selectDashboard(value: MobileDashboard): void { if (!value.id) return; this.selectedDashboardId.set(value.id); this.render.set(null); this.busy.set(true); this.api.render(value.id).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: result => this.render.set(result), error: error => this.error.set(normalizeApiError(error).message || 'Dashboard oluşturulamadı.') }); }
  protected exportDashboard(): void { const dashboard = this.selectedDashboard(); if (!dashboard?.id || this.connectivity.offline() || this.busy()) return; this.busy.set(true); this.api.export(dashboard.id).pipe(finalize(() => this.busy.set(false)), takeUntilDestroyed(this.destroyRef)).subscribe({ next: blob => { const url = URL.createObjectURL(blob), anchor = this.document.createElement('a'); anchor.href = url; anchor.download = `${dashboard.name.replace(/[^a-z0-9-_]+/gi, '-').toLowerCase() || 'dashboard'}.json`; anchor.click(); URL.revokeObjectURL(url); this.notice.set('Dashboard dışa aktarıldı.'); }, error: value => this.error.set(normalizeApiError(value).message || 'Dashboard dışa aktarılamadı.') }); }
  protected userName(id?: string | null): string { if (!id) return 'Atanmamış'; const user = this.data()?.users.find(item => item.id === id); return user?.username || user?.email || 'Atanmamış'; }
  protected statusLabel(key: string): string { return this.data() ? mobileWorkflowLabel(this.data()!, key) : key; }
  protected days(hours?: number | null): string { return mobileReportDays(hours); }
  protected dashboardState = mobileDashboardState; protected dashboardType = mobileDashboardTypeLabel; protected cell = mobileDashboardCell;
  protected projectName(id: string): string { return this.workspace.projects().find(item => item.id === id)?.name ?? (id === this.projectId ? this.project()?.name ?? 'Proje' : 'Erişilebilir proje'); }
  private initialTab(): MobileReportingTab { const data = this.route.snapshot.data['tab'], query = this.route.snapshot.queryParamMap.get('mode') ?? this.route.snapshot.queryParamMap.get('tab'); return this.asTab(typeof data === 'string' ? data : query); }
  private initialRange(): 30 | 90 | 180 { const value = Number(this.route.snapshot.queryParamMap.get('range')); return value === 90 || value === 180 ? value : 30; }
  private asTab(value: string | null): MobileReportingTab { return value === 'workload' || value === 'dashboards' ? value : 'reports'; }
}
