export type MobileAutomationTab = 'rules' | 'runs' | 'templates' | 'recurrences';

export interface MobileAutomationRole { readonly name: string; readonly permissions: readonly string[]; readonly isActive: boolean; }
export interface MobileAutomationUser { readonly id: string; readonly username?: string | null; readonly email?: string | null; }
export interface MobileAutomationProject { readonly id: string; readonly key: string; readonly name: string; readonly members?: readonly { readonly userId: string; readonly role?: string | null }[]; }
export interface MobileAutomationBoard { readonly id: string; readonly name: string; readonly archived?: boolean; }
export interface MobileAutomationIssueType { readonly key: string; readonly name: string; readonly active: boolean; readonly position: number; }
export interface MobileAutomationSchema { readonly issueTypes: readonly MobileAutomationIssueType[]; }
export interface MobileAutomationPage<T> { readonly items: readonly T[]; readonly page: number; readonly pageSize: number; readonly total?: number; readonly totalCount?: number; }

export interface MobileAutomationAction { readonly type: string; readonly value?: string | null; }
export interface MobileAutomationCondition { readonly kind: string; readonly field?: string | null; readonly operator?: string | null; readonly value?: string | null; readonly children: readonly MobileAutomationCondition[]; }
export interface MobileAutomationTrigger { readonly type: 'Event' | 'Schedule'; readonly eventType?: string | null; readonly intervalMinutes?: number | null; readonly startAtUtc?: string | null; }
export interface MobileAutomationRuleDefinition { readonly number: number; readonly state: string; readonly name: string; readonly description?: string | null; readonly trigger: MobileAutomationTrigger; readonly condition?: MobileAutomationCondition | null; readonly actions: readonly MobileAutomationAction[]; readonly maximumExecutionsPerHour: number; readonly maximumChainDepth: number; }
export interface MobileAutomationRuleSummary { readonly id: string; readonly projectId: string; readonly name: string; readonly triggerType: string; readonly eventType?: string | null; readonly active: boolean; readonly archived: boolean; readonly nextRunAtUtc?: string | null; readonly publishedVersion: number; readonly hasDraft: boolean; readonly version: number; }
export interface MobileAutomationRule extends Omit<MobileAutomationRuleSummary, 'name' | 'triggerType' | 'eventType'> { readonly definition?: MobileAutomationRuleDefinition | null; }
export interface MobileAutomationRuleDraft { readonly id?: string | null; readonly name: string; readonly description: string; readonly triggerType: 'Event' | 'Schedule'; readonly eventType: string; readonly intervalMinutes: number; readonly startAtLocal: string; readonly conditionMode: 'All' | 'Any'; readonly conditions: readonly MobileAutomationConditionDraft[]; readonly actions: readonly MobileAutomationActionDraft[]; readonly maximumExecutionsPerHour: number; readonly maximumChainDepth: number; }
export interface MobileAutomationConditionDraft { readonly field: string; readonly operator: string; readonly value: string; }
export interface MobileAutomationActionDraft { readonly type: string; readonly value: string; }
export interface MobileAutomationDryRunInput { readonly sourceId: string; readonly status: string; readonly previousStatus: string; readonly priority: string; readonly type: string; readonly assigneeUserId: string; readonly labels: string; }
export interface MobileAutomationDryRun { readonly ruleId: string; readonly ruleVersion: number; readonly triggerMatched: boolean; readonly conditionMatched: boolean; readonly plannedActions: readonly MobileAutomationAction[]; readonly outcome: string; }

export interface MobileAutomationRunStep { readonly index: number; readonly actionType: string; readonly status: string; readonly attempt: number; readonly failureCategory?: string | null; readonly completedAtUtc?: string | null; }
export interface MobileAutomationRun { readonly id: string; readonly projectId: string; readonly ruleId: string; readonly ruleVersion: number; readonly ruleName: string; readonly triggerType: string; readonly eventType?: string | null; readonly sourceId?: string | null; readonly chainDepth: number; readonly status: string; readonly outcome: string; readonly attempt: number; readonly maximumAttempts: number; readonly failureCategory?: string | null; readonly createdAtUtc: string; readonly nextAttemptAtUtc?: string | null; readonly steps: readonly MobileAutomationRunStep[]; readonly version: number; }

export interface MobileWorkTemplate { readonly id: string; readonly projectId: string; readonly boardId: string; readonly name: string; readonly title: string; readonly description: string; readonly type: string; readonly priority: string; readonly assigneeUserId?: string | null; readonly teamId?: string | null; readonly dueAfterDays?: number | null; readonly labels: readonly string[]; readonly customFields: readonly unknown[]; readonly archived: boolean; readonly version: number; }
export interface MobileWorkTemplateDraft { readonly id?: string | null; readonly version?: number; readonly boardId: string; readonly name: string; readonly title: string; readonly description: string; readonly type: string; readonly priority: string; readonly assigneeUserId: string; readonly dueAfterDays: number | null; readonly labelsText: string; readonly customFields: readonly unknown[]; }
export interface MobileWorkRecurrence { readonly id: string; readonly projectId: string; readonly templateId: string; readonly frequency: string; readonly interval: number; readonly startAtUtc: string; readonly endAtUtc?: string | null; readonly nextRunAtUtc?: string | null; readonly maxOccurrences: number; readonly scheduledOccurrences: number; readonly generatedOccurrences: number; readonly active: boolean; readonly archived: boolean; readonly version: number; }
export interface MobileWorkRecurrenceDraft { readonly templateId: string; readonly frequency: string; readonly interval: number; readonly startAtLocal: string; readonly endAtLocal: string; readonly maxOccurrences: number; }
export interface MobileWorkRecurrencePreview { readonly frequency: string; readonly interval: number; readonly occurrencesUtc: readonly string[]; }
export interface MobileWorkRecurrenceOccurrence { readonly id: string; readonly scheduledForUtc: string; readonly status: string; readonly createdWorkItemId?: string | null; readonly version: number; }
export interface MobileAutomationAudit { readonly id: string; readonly action: string; readonly actorUserId?: string | null; readonly createdAt: string; }
export interface MobileAutomationContext { readonly project: MobileAutomationProject; readonly boards: readonly MobileAutomationBoard[]; readonly rules: readonly MobileAutomationRuleSummary[]; readonly runs: readonly MobileAutomationRun[]; readonly templates: readonly MobileWorkTemplate[]; readonly recurrences: readonly MobileWorkRecurrence[]; readonly roles: readonly MobileAutomationRole[]; readonly users: readonly MobileAutomationUser[]; readonly schema: MobileAutomationSchema; }
