import { Injectable, inject } from '@angular/core';
import { ZumboApiClient, normalizeApiError } from '@zumbo/modern-shared';
import { Observable, catchError, forkJoin, map, throwError } from 'rxjs';
import { MobileAutomationAudit, MobileAutomationBoard, MobileAutomationContext, MobileAutomationDryRun, MobileAutomationDryRunInput, MobileAutomationPage, MobileAutomationProject, MobileAutomationRole, MobileAutomationRule, MobileAutomationRuleDraft, MobileAutomationRuleSummary, MobileAutomationRun, MobileAutomationSchema, MobileAutomationUser, MobileWorkRecurrence, MobileWorkRecurrenceDraft, MobileWorkRecurrenceOccurrence, MobileWorkRecurrencePreview, MobileWorkTemplate, MobileWorkTemplateDraft } from './mobile-automation.models';
import { mobileAutomationRuleRequest, mobileWorkRecurrenceRequest, mobileWorkTemplateRequest } from './mobile-automation.core';

@Injectable()
export class MobileAutomationService {
  private readonly api = inject(ZumboApiClient);

  load(projectId: string): Observable<MobileAutomationContext> { const id = encodeURIComponent(projectId); return forkJoin({ project: this.api.get<MobileAutomationProject>(`/api/projects/${id}`), boards: this.api.get<readonly MobileAutomationBoard[]>(`/api/boards/by-project/${id}`), rules: this.api.get<MobileAutomationPage<MobileAutomationRuleSummary>>(`/api/automations?projectId=${id}&page=1&pageSize=100`), runs: this.api.get<MobileAutomationPage<MobileAutomationRun>>(`/api/automations/runs?projectId=${id}&page=1&pageSize=100`), templates: this.api.get<MobileAutomationPage<MobileWorkTemplate>>(`/api/work-items/templates?projectId=${id}`), recurrences: this.api.get<MobileAutomationPage<MobileWorkRecurrence>>(`/api/work-items/recurrences?projectId=${id}`), roles: this.api.get<readonly MobileAutomationRole[]>('/api/auth/roles?scope=Project'), users: this.api.get<readonly MobileAutomationUser[]>('/api/auth/users'), schema: this.api.get<MobileAutomationSchema>(`/api/work-item-schemas/${id}`) }).pipe(map(data => ({ ...data, rules: data.rules.items, runs: data.runs.items, templates: data.templates.items, recurrences: data.recurrences.items }))); }
  rule(id: string, draft: boolean): Observable<MobileAutomationRule> { const path = `/api/automations/${encodeURIComponent(id)}`; return this.api.get<MobileAutomationRule>(draft ? `${path}?draft=true` : path).pipe(catchError(error => draft && normalizeApiError(error).code === 'AUTOMATION_DRAFT_NOT_FOUND' ? this.api.get<MobileAutomationRule>(path) : throwError(() => error))); }
  saveRule(projectId: string, draft: MobileAutomationRuleDraft): Observable<MobileAutomationRule> { const body = mobileAutomationRuleRequest(projectId, draft); return draft.id ? this.api.put<MobileAutomationRule>(`/api/automations/${encodeURIComponent(draft.id)}/draft`, body) : this.api.post<MobileAutomationRule>('/api/automations', body); }
  publishRule(id: string): Observable<MobileAutomationRule> { return this.api.post<MobileAutomationRule>(`/api/automations/${encodeURIComponent(id)}/publish`, {}); }
  setRuleState(id: string, active: boolean, version: number): Observable<MobileAutomationRule> { return this.api.patch<MobileAutomationRule>(`/api/automations/${encodeURIComponent(id)}/state`, { active }, { ifMatch: version }); }
  archiveRule(id: string, version: number): Observable<void> { return this.api.delete<void>(`/api/automations/${encodeURIComponent(id)}`, { ifMatch: version }); }
  dryRun(id: string, input: MobileAutomationDryRunInput, triggerType: 'Event' | 'Schedule', eventType: string): Observable<MobileAutomationDryRun> { return this.api.post<MobileAutomationDryRun>(`/api/automations/${encodeURIComponent(id)}/dry-run`, { triggerType, eventType: triggerType === 'Event' ? eventType : null, sourceId: input.sourceId || null, fields: { Status: input.status || null, PreviousStatus: input.previousStatus || null, Priority: input.priority || null, Type: input.type || null, AssigneeUserId: input.assigneeUserId || null, Labels: input.labels || null } }); }
  runs(projectId: string, status: string): Observable<MobileAutomationPage<MobileAutomationRun>> { const filter = status ? `&status=${encodeURIComponent(status)}` : ''; return this.api.get<MobileAutomationPage<MobileAutomationRun>>(`/api/automations/runs?projectId=${encodeURIComponent(projectId)}&page=1&pageSize=100${filter}`); }
  replayRun(id: string, version: number): Observable<MobileAutomationRun> { return this.api.post<MobileAutomationRun>(`/api/automations/runs/${encodeURIComponent(id)}/replay`, {}, { ifMatch: version }); }
  saveTemplate(projectId: string, draft: MobileWorkTemplateDraft): Observable<MobileWorkTemplate> { const body = mobileWorkTemplateRequest(projectId, draft); return draft.id ? this.api.put<MobileWorkTemplate>(`/api/work-items/templates/${encodeURIComponent(draft.id)}`, body, { ifMatch: draft.version }) : this.api.post<MobileWorkTemplate>('/api/work-items/templates', body); }
  archiveTemplate(id: string, version: number): Observable<void> { return this.api.delete<void>(`/api/work-items/templates/${encodeURIComponent(id)}`, { ifMatch: version }); }
  previewRecurrence(projectId: string, draft: MobileWorkRecurrenceDraft): Observable<MobileWorkRecurrencePreview> { return this.api.post<MobileWorkRecurrencePreview>('/api/work-items/recurrences/preview', { ...(mobileWorkRecurrenceRequest(projectId, draft) as object), previewCount: 5 }); }
  createRecurrence(projectId: string, draft: MobileWorkRecurrenceDraft): Observable<MobileWorkRecurrence> { return this.api.post<MobileWorkRecurrence>('/api/work-items/recurrences', mobileWorkRecurrenceRequest(projectId, draft)); }
  setRecurrenceState(id: string, active: boolean, version: number): Observable<MobileWorkRecurrence> { return this.api.patch<MobileWorkRecurrence>(`/api/work-items/recurrences/${encodeURIComponent(id)}/state`, { active }, { ifMatch: version }); }
  archiveRecurrence(id: string, version: number): Observable<void> { return this.api.delete<void>(`/api/work-items/recurrences/${encodeURIComponent(id)}`, { ifMatch: version }); }
  occurrences(id: string): Observable<MobileAutomationPage<MobileWorkRecurrenceOccurrence>> { return this.api.get<MobileAutomationPage<MobileWorkRecurrenceOccurrence>>(`/api/work-items/recurrences/${encodeURIComponent(id)}/occurrences?page=1&pageSize=100`); }
  audit(type: 'AutomationRule' | 'WorkItemTemplate' | 'WorkItemRecurrence', id: string): Observable<readonly MobileAutomationAudit[]> { return this.api.get<readonly MobileAutomationAudit[]>(`/api/audit/entity/${type}/${encodeURIComponent(id)}`); }
}
