import { MobileAutomationActionDraft, MobileAutomationConditionDraft, MobileAutomationRole, MobileAutomationRule, MobileAutomationRuleDraft, MobileAutomationRuleSummary, MobileWorkRecurrence, MobileWorkRecurrenceDraft, MobileWorkTemplate, MobileWorkTemplateDraft } from './mobile-automation.models';

export const mobileAutomationLimits = Object.freeze({ ruleConditions: 20, ruleActions: 10, ruleHourlyLimit: 1000, ruleChainDepth: 10, recurrenceInterval: 365, recurrenceOccurrences: 366, labelCount: 50, labelLength: 50 });
export const mobileAutomationEventTypes = Object.freeze([{ value: 'WorkItemCreated', label: 'İş oluşturulduğunda' }, { value: 'WorkItemUpdated', label: 'İş güncellendiğinde' }, { value: 'WorkItemTransitioned', label: 'İş durum değiştirdiğinde' }]);
export const mobileAutomationConditionFields = Object.freeze(['Status', 'PreviousStatus', 'Priority', 'Type', 'AssigneeUserId', 'Labels']);
export const mobileAutomationConditionOperators = Object.freeze(['Equals', 'NotEquals', 'Contains', 'NotContains', 'IsEmpty', 'IsNotEmpty']);
export const mobileAutomationActionTypes = Object.freeze(['AssignToActor', 'AssignUser', 'ClearAssignee', 'AddLabel', 'RemoveLabel', 'SetPriority', 'AddComment']);

export function hasMobileAutomationPermission(roleName: string | null, roles: readonly MobileAutomationRole[], permission: string): boolean { const role = roles.find(item => item.name === roleName && item.isActive); return !!role?.permissions.some(item => item === '*' || item === permission); }
export function newMobileAutomationRuleDraft(): MobileAutomationRuleDraft { return { name: '', description: '', triggerType: 'Event', eventType: 'WorkItemCreated', intervalMinutes: 60, startAtLocal: '', conditionMode: 'All', conditions: [], actions: [{ type: 'AddLabel', value: '' }], maximumExecutionsPerHour: 100, maximumChainDepth: 3 }; }
export function mobileAutomationRuleDraft(rule: MobileAutomationRule): MobileAutomationRuleDraft { const definition = rule.definition; const condition = definition?.condition; const conditions = !condition ? [] : condition.kind === 'Field' ? [condition] : condition.children; return { id: rule.id, name: definition?.name ?? '', description: definition?.description ?? '', triggerType: definition?.trigger.type ?? 'Event', eventType: definition?.trigger.eventType ?? 'WorkItemCreated', intervalMinutes: definition?.trigger.intervalMinutes ?? 60, startAtLocal: toLocalInput(definition?.trigger.startAtUtc), conditionMode: condition?.kind === 'Any' ? 'Any' : 'All', conditions: conditions.map(item => ({ field: item.field ?? 'Status', operator: item.operator ?? 'Equals', value: item.value ?? '' })), actions: (definition?.actions ?? []).map(item => ({ type: item.type, value: item.value ?? '' })), maximumExecutionsPerHour: definition?.maximumExecutionsPerHour ?? 100, maximumChainDepth: definition?.maximumChainDepth ?? 3 }; }
export function mobileAutomationRuleRequest(projectId: string, draft: MobileAutomationRuleDraft): unknown { const conditions = draft.conditions.map(item => ({ kind: 'Field', field: item.field, operator: item.operator, value: mobileAutomationConditionNeedsValue(item.operator) ? item.value.trim() : null, children: [] })); return { projectId, name: draft.name.trim(), description: draft.description.trim() || null, trigger: draft.triggerType === 'Schedule' ? { type: 'Schedule', eventType: null, intervalMinutes: Number(draft.intervalMinutes), startAtUtc: toUtc(draft.startAtLocal) } : { type: 'Event', eventType: draft.eventType, intervalMinutes: null, startAtUtc: null }, condition: conditions.length === 0 ? null : conditions.length === 1 ? conditions[0] : { kind: draft.conditionMode, field: null, operator: null, value: null, children: conditions }, actions: draft.actions.map(item => ({ type: item.type, value: mobileAutomationActionNeedsValue(item.type) ? item.value.trim() : null })), maximumExecutionsPerHour: Number(draft.maximumExecutionsPerHour), maximumChainDepth: Number(draft.maximumChainDepth) }; }
export function validMobileAutomationRule(draft: MobileAutomationRuleDraft): boolean { return !!draft.name.trim() && draft.actions.length > 0 && draft.actions.length <= mobileAutomationLimits.ruleActions && draft.conditions.length <= mobileAutomationLimits.ruleConditions && (draft.triggerType !== 'Schedule' || (draft.intervalMinutes >= 5 && !!draft.startAtLocal)) && draft.maximumExecutionsPerHour >= 1 && draft.maximumExecutionsPerHour <= mobileAutomationLimits.ruleHourlyLimit && draft.maximumChainDepth >= 1 && draft.maximumChainDepth <= mobileAutomationLimits.ruleChainDepth && draft.conditions.every(item => !mobileAutomationConditionNeedsValue(item.operator) || !!item.value.trim()) && draft.actions.every(item => !mobileAutomationActionNeedsValue(item.type) || !!item.value.trim()); }
export function mobileAutomationActionNeedsValue(type: string): boolean { return ['AssignUser', 'AddLabel', 'RemoveLabel', 'SetPriority', 'AddComment'].includes(type); }
export function mobileAutomationConditionNeedsValue(type: string): boolean { return !['IsEmpty', 'IsNotEmpty'].includes(type); }
export function mobileAutomationConditionFieldLabel(value: string): string { return ({ Status: 'Durum', PreviousStatus: 'Önceki durum', Priority: 'Öncelik', Type: 'İş türü', AssigneeUserId: 'Atanan kullanıcı', Labels: 'Etiketler' } as Readonly<Record<string, string>>)[value] ?? value; }
export function mobileAutomationConditionOperatorLabel(value: string): string { return ({ Equals: 'Eşittir', NotEquals: 'Eşit değildir', Contains: 'İçerir', NotContains: 'İçermez', IsEmpty: 'Boş', IsNotEmpty: 'Boş değil' } as Readonly<Record<string, string>>)[value] ?? value; }
export function mobileAutomationActionTypeLabel(value: string): string { return ({ AssignToActor: 'Tetikleyen kullanıcıya ata', AssignUser: 'Kullanıcıya ata', ClearAssignee: 'Atamayı kaldır', AddLabel: 'Etiket ekle', RemoveLabel: 'Etiketi kaldır', SetPriority: 'Öncelik ayarla', AddComment: 'Yorum ekle' } as Readonly<Record<string, string>>)[value] ?? value; }
export function mobileAutomationRuleState(rule: MobileAutomationRuleSummary): string { return rule.archived ? 'Arşiv' : !rule.publishedVersion ? 'Taslak' : rule.active ? 'Etkin' : 'Duraklatıldı'; }
export function mobileAutomationTriggerLabel(rule: MobileAutomationRuleSummary): string { return rule.triggerType === 'Schedule' ? 'Zamanlanmış' : mobileAutomationEventTypes.find(item => item.value === rule.eventType)?.label ?? 'Olay'; }
export function mobileAutomationRunState(value: string): string { return ({ Succeeded: 'Başarılı', Skipped: 'Atlandı', Running: 'Çalışıyor', Pending: 'Sırada', RetryScheduled: 'Yeniden denenecek', DeadLetter: 'Müdahale gerekli' } as Readonly<Record<string, string>>)[value] ?? (value || 'Bilinmiyor'); }
export function mobileAutomationAuditActionLabel(value: string): string { return ({ AutomationCreated: 'Otomasyon oluşturuldu', AutomationDraftSaved: 'Otomasyon taslağı kaydedildi', AutomationPublished: 'Otomasyon yayınlandı', AutomationStateChanged: 'Otomasyon durumu değiştirildi', AutomationArchived: 'Otomasyon arşivlendi', WorkItemTemplateCreated: 'İş şablonu oluşturuldu', WorkItemTemplateUpdated: 'İş şablonu güncellendi', WorkItemTemplateArchived: 'İş şablonu arşivlendi', WorkItemRecurrenceCreated: 'Yineleme oluşturuldu', WorkItemRecurrenceStateChanged: 'Yineleme durumu değiştirildi', WorkItemRecurrenceArchived: 'Yineleme arşivlendi' } as Readonly<Record<string, string>>)[value] ?? 'Otomasyon etkinliği'; }

export function newMobileWorkTemplateDraft(boardId: string, type: string): MobileWorkTemplateDraft { return { boardId, name: '', title: '', description: '', type, priority: 'Medium', assigneeUserId: '', dueAfterDays: null, labelsText: '', customFields: [] }; }
export function mobileWorkTemplateDraft(value: MobileWorkTemplate): MobileWorkTemplateDraft { return { id: value.id, version: value.version, boardId: value.boardId, name: value.name, title: value.title, description: value.description, type: value.type, priority: value.priority, assigneeUserId: value.assigneeUserId ?? '', dueAfterDays: value.dueAfterDays ?? null, labelsText: value.labels.join(', '), customFields: value.customFields }; }
export function mobileWorkTemplateRequest(projectId: string, draft: MobileWorkTemplateDraft): unknown { return { ...(draft.id ? {} : { projectId }), boardId: draft.boardId, name: draft.name.trim(), title: draft.title.trim(), description: draft.description.trim() || null, type: draft.type, priority: draft.priority, assigneeUserId: draft.assigneeUserId || null, teamId: null, dueAfterDays: draft.dueAfterDays, labels: mobileAutomationLabels(draft.labelsText).values, customFields: draft.customFields }; }
export function mobileAutomationLabels(value: string): { readonly values: readonly string[]; readonly tooMany: boolean; readonly tooLong: boolean } { const raw = value.split(/[\n,]+/).map(item => item.trim()).filter(Boolean); const seen = new Set<string>(); const values = raw.filter(item => { const key = item.toLocaleLowerCase('tr-TR'); if (seen.has(key)) return false; seen.add(key); return true; }); return { values: values.slice(0, mobileAutomationLimits.labelCount), tooMany: values.length > mobileAutomationLimits.labelCount, tooLong: values.some(item => item.length > mobileAutomationLimits.labelLength) }; }
export function newMobileWorkRecurrenceDraft(templateId = ''): MobileWorkRecurrenceDraft { const date = new Date(Date.now() + 15 * 60_000); date.setSeconds(0, 0); return { templateId, frequency: 'Weekly', interval: 1, startAtLocal: toLocalInput(date.toISOString()), endAtLocal: '', maxOccurrences: 12 }; }
export function mobileWorkRecurrenceRequest(projectId: string, draft: MobileWorkRecurrenceDraft): unknown { return { projectId, templateId: draft.templateId, frequency: draft.frequency, interval: Number(draft.interval), startAtUtc: toUtc(draft.startAtLocal), endAtUtc: toUtc(draft.endAtLocal), maxOccurrences: Number(draft.maxOccurrences) }; }
export function validMobileWorkRecurrence(draft: MobileWorkRecurrenceDraft): boolean { return !!draft.templateId && !!draft.startAtLocal && draft.interval >= 1 && draft.interval <= mobileAutomationLimits.recurrenceInterval && draft.maxOccurrences >= 1 && draft.maxOccurrences <= mobileAutomationLimits.recurrenceOccurrences; }
export function mobileWorkRecurrenceState(value: MobileWorkRecurrence): string { return value.archived ? 'Arşiv' : !value.nextRunAtUtc || value.scheduledOccurrences >= value.maxOccurrences ? 'Tamamlandı' : value.active ? 'Etkin' : 'Duraklatıldı'; }
export function mobileWorkRecurrenceFrequency(value: MobileWorkRecurrence): string { const unit = ({ Daily: 'gün', Weekly: 'hafta', Monthly: 'ay' } as Readonly<Record<string, string>>)[value.frequency] ?? 'dönem'; return value.interval === 1 ? `Her ${unit}` : `Her ${value.interval} ${unit}`; }
export function mobileWorkOccurrenceState(value: string): string { return ({ Scheduled: 'Planlandı', Generated: 'Oluşturuldu', Skipped: 'Atlandı', Failed: 'Başarısız', Cancelled: 'İptal edildi' } as Readonly<Record<string, string>>)[value] ?? (value || 'Bilinmiyor'); }
export function mobileAutomationError(error: { readonly message?: string } | null | undefined, fallback: string): string { return error?.message || fallback; }

function toUtc(value?: string | null): string | null { if (!value) return null; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString(); }
function toLocalInput(value?: string | null): string { if (!value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
