import { CommonModule } from '@angular/common';import { Component,DestroyRef,OnInit,computed,inject,input,signal } from '@angular/core';import { takeUntilDestroyed } from '@angular/core/rxjs-interop';import { FormsModule } from '@angular/forms';import { finalize } from 'rxjs';
import { ProjectSummary } from '../../shell/desktop-shell.models';import { ZumboIconComponent } from '../../shell/zumbo-icon.component';
import { canManageProject,newAllocation,newDraft,scenarioDelta,stateLabel,validateCapacity } from './capacity.core';
import { CapacityAllocation,CapacityDraft,CapacityPlan,CapacityPortfolio,CapacityRole,CapacityScenario,CapacitySnapshot,CapacityTab,CapacityTeam,CapacityUser } from './capacity.models';import { CapacityService } from './capacity.service';
@Component({selector:'zumbo-capacity-page',imports:[CommonModule,FormsModule,ZumboIconComponent],providers:[CapacityService],templateUrl:'./capacity.page.html',styleUrls:['./capacity.page.scss','./capacity-layout.scss','./capacity-responsive.scss','./capacity-theme.scss']})
export class CapacityPage implements OnInit{readonly projects=input.required<readonly ProjectSummary[]>();readonly userId=input.required<string>();private readonly api=inject(CapacityService);private readonly destroyRef=inject(DestroyRef);
 protected readonly loading=signal(true);protected readonly busy=signal(false);protected readonly error=signal<string|null>(null);protected readonly notice=signal<string|null>(null);protected readonly plans=signal<readonly CapacityPlan[]>([]);protected readonly users=signal<readonly CapacityUser[]>([]);protected readonly roles=signal<readonly CapacityRole[]>([]);protected readonly portfolios=signal<readonly CapacityPortfolio[]>([]);protected readonly teams=signal<readonly CapacityTeam[]>([]);protected readonly selected=signal<CapacityPlan|null>(null);protected readonly snapshot=signal<CapacitySnapshot|null>(null);protected readonly scenario=signal<CapacityScenario|null>(null);protected readonly tab=signal<CapacityTab>('people');protected draft:CapacityDraft=newDraft('');protected scenarioRows:CapacityAllocation[]=[];
 protected readonly manageable=computed(()=>this.projects().filter(p=>canManageProject(p,this.userId(),this.roles())));protected readonly canCreate=computed(()=>this.manageable().length>0);protected readonly stateLabel=stateLabel;
 ngOnInit(){this.load();}
 protected load(){this.loading.set(true);this.error.set(null);this.api.context(this.projects()[0]?.organizationId??'').pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:({page,portfolios,users,roles,teams})=>{this.plans.set(page.items);this.portfolios.set(portfolios.items);this.users.set(users);this.roles.set(roles);this.teams.set(teams);const next=page.items.find(x=>x.id===this.selected()?.id)??page.items[0];next?this.select(next):this.create();},error:e=>this.fail(e,'Kapasite planları yüklenemedi.')});}
 protected select(p:CapacityPlan){this.busy.set(true);this.api.detail(p.id).pipe(finalize(()=>this.busy.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:({plan,snapshot})=>{this.selected.set(plan);this.snapshot.set(snapshot);this.draft=newDraft(this.userId(),plan);this.scenarioRows=plan.allocations.map(x=>({...x}));this.scenario.set(null);this.tab.set('people');},error:e=>this.fail(e,'Kapasite planı yüklenemedi.')});}
 protected create(){if(!this.canCreate()){this.selected.set(null);return;}this.selected.set(null);this.snapshot.set(null);this.draft=newDraft(this.userId());this.tab.set('definition');}
 protected save(){if(this.selected()&&!this.selected()?.canEdit)return;const m=validateCapacity(this.draft);if(m)return this.error.set(m);this.mutate(this.api.save(this.draft),this.draft.id?'Kapasite planı güncellendi.':'Kapasite planı oluşturuldu.',p=>{this.selected.set(p);this.load();});}
 protected share(){const p=this.selected();if(!p?.canEdit)return;this.mutate(this.api.share(p,this.draft.viewerUserIds),'Paylaşım güncellendi.',x=>{this.selected.set(x);this.draft=newDraft(this.userId(),x);});}
 protected archive(){const p=this.selected();if(!p?.canEdit||!confirm('Bu kapasite planını arşivlemek istiyor musunuz?'))return;this.mutate(this.api.archive(p),'Kapasite planı arşivlendi.',()=>{this.selected.set(null);this.load();});}
 protected addMember(){this.draft.members.push({userId:'',teamId:null,weeklyCapacityHours:40});}protected removeMember(i:number){if(this.draft.members.length<=1)return;const [m]=this.draft.members.splice(i,1);this.draft.allocations=this.draft.allocations.filter(x=>x.userId!==m.userId);}
 protected addAllocation(rows=this.draft.allocations){rows.push(newAllocation(this.draft));}protected removeAllocation(rows:CapacityAllocation[],i:number){rows.splice(i,1);}
 protected preview(){const p=this.selected(),m=validateCapacity(this.draft,this.scenarioRows);if(!p?.canEdit)return;if(m)return this.error.set(m);this.mutate(this.api.scenario(p,this.scenarioRows),'Senaryo hesaplandı; kayıtlı plan değişmedi.',x=>this.scenario.set(x));}
 protected resetScenario(){this.scenarioRows=this.selected()?.allocations.map(x=>({...x}))??[];this.scenario.set(null);}protected delta(k:keyof CapacitySnapshot['summary']){return scenarioDelta(this.scenario(),k);}
 protected toggle(field:'projectIds'|'viewerUserIds',id:string,on:boolean){const values=this.draft[field];this.draft[field]=on?[...new Set([...values,id])]:values.filter(x=>x!==id);}
 protected projectOptions(){return this.projects().filter(p=>this.draft.projectIds.includes(p.id)||canManageProject(p,this.userId(),this.roles()));}
 protected userName(id:string){const u=this.users().find(x=>x.id===id);return u?.username||u?.email||'Erişilemeyen kullanıcı';}protected projectName(id:string){return this.projects().find(x=>x.id===id)?.name??'Erişilemeyen proje';}
 private mutate<T>(r:import('rxjs').Observable<T>,message:string,done:(x:T)=>void){if(this.busy())return;this.busy.set(true);this.error.set(null);r.pipe(finalize(()=>this.busy.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:x=>{this.notice.set(message);done(x);},error:e=>this.fail(e,'İşlem tamamlanamadı.')});}private fail(e:any,f:string){this.error.set(e?.message??f);}
}
