import { ProjectSummary } from '../../shell/desktop-shell.models';
import { CapacityAllocation,CapacityDraft,CapacityPlan,CapacityRole } from './capacity.models';
export const CAPACITY_LIMITS={projects:20,members:100,allocations:500,viewers:50,days:366} as const;
export function newDraft(userId:string,item?:CapacityPlan):CapacityDraft{const start=monday(),end=addDays(start,27);return{id:item?.id,name:item?.name??'',description:item?.description??'',periodStart:item?.periodStart??start,periodEnd:item?.periodEnd??end,portfolioId:item?.portfolioId??'',projectIds:[...(item?.projectIds??[])],members:item?.members.map(x=>({...x}))??(userId?[{userId,teamId:null,weeklyCapacityHours:40}]:[]),allocations:item?.allocations.map(x=>({...x}))??[],viewerUserIds:[...(item?.viewerUserIds??[])],version:item?.version};}
export function newAllocation(d:CapacityDraft):CapacityAllocation{return{id:null,userId:d.members[0]?.userId??'',projectId:d.projectIds[0]??'',startDate:d.periodStart,endDate:d.periodEnd,percent:100};}
export function validateCapacity(d:CapacityDraft,rows=d.allocations):string|null{if(!d.name.trim())return'Plan adı zorunludur.';if(d.name.trim().length>120)return'Plan adı 120 karakteri aşamaz.';if(d.description.length>500)return'Açıklama 500 karakteri aşamaz.';if(!d.periodStart||!d.periodEnd||d.periodEnd<d.periodStart)return'Geçerli bir plan dönemi seçin.';if(days(d.periodStart,d.periodEnd)>366)return'Plan dönemi 366 günü aşamaz.';if(!d.projectIds.length)return'En az bir proje seçin.';if(!d.members.length)return'En az bir kişi ekleyin.';const ids=new Set<string>();for(const m of d.members){if(!m.userId)return'Her kapasite satırı için bir kişi seçin.';if(ids.has(m.userId))return'Bir kişi plana yalnızca bir kez eklenebilir.';ids.add(m.userId);if(m.weeklyCapacityHours<0||m.weeklyCapacityHours>168)return'Haftalık kapasite 0 ile 168 saat arasında olmalıdır.';}for(const r of rows){if(!ids.has(r.userId))return'Her tahsis plandaki bir kişiye bağlı olmalıdır.';if(!d.projectIds.includes(r.projectId))return'Her tahsis plan kapsamındaki bir projeye bağlı olmalıdır.';if(r.startDate<d.periodStart||r.endDate>d.periodEnd||r.endDate<r.startDate)return'Tahsis tarihleri plan dönemi içinde olmalıdır.';if(r.percent<=0||r.percent>100)return'Tahsis oranı %1 ile %100 arasında olmalıdır.';}return null;}
export function canManageProject(project:ProjectSummary,userId:string,roles:readonly CapacityRole[]){const role=project.members?.find(x=>x.userId===userId)?.role;return!!role&&!!roles.find(x=>x.isActive&&x.name===role)?.permissions.includes('BoardManage');}
export function stateLabel(v:string){return({Available:'Uygun',NearCapacity:'Sınıra yakın',OverCapacity:'Kapasite üstü'} as Record<string,string>)[v]??'Bilinmiyor';}
export function scenarioDelta(s:import('./capacity.models').CapacityScenario|null,key:keyof import('./capacity.models').CapacitySummary){return s?Number(s.candidate.summary[key])-Number(s.baseline.summary[key]):0;}
function monday(){const d=new Date(),offset=d.getDay()===0?-6:1-d.getDay();return dateKey(new Date(d.getFullYear(),d.getMonth(),d.getDate()+offset));}function addDays(v:string,n:number){const d=new Date(v+'T00:00:00');d.setDate(d.getDate()+n);return dateKey(d);}function dateKey(d:Date){return d.toISOString().slice(0,10);}function days(a:string,b:string){return Math.round((Date.parse(b)-Date.parse(a))/86400000)+1;}
