import { Injectable,inject } from '@angular/core';import { ZumboApiClient } from '@zumbo/modern-shared';import { forkJoin,Observable } from 'rxjs';
import { CapacityDraft,CapacityPage,CapacityPlan,CapacityPortfolio,CapacityRole,CapacityScenario,CapacitySnapshot,CapacityTeam,CapacityUser } from './capacity.models';
@Injectable()export class CapacityService{private readonly api=inject(ZumboApiClient);
 context(organizationId:string){return forkJoin({page:this.api.get<CapacityPage>('/api/capacity-plans?page=1&pageSize=100'),portfolios:this.api.get<{readonly items:readonly CapacityPortfolio[]}>('/api/portfolios?page=1&pageSize=100'),users:this.api.get<readonly CapacityUser[]>('/api/auth/users'),roles:this.api.get<readonly CapacityRole[]>('/api/auth/roles?scope=Project'),teams:this.api.get<readonly CapacityTeam[]>(`/api/teams?organizationId=${encodeURIComponent(organizationId)}`)});}
 detail(id:string){const p=encodeURIComponent(id);return forkJoin({plan:this.api.get<CapacityPlan>(`/api/capacity-plans/${p}`),snapshot:this.api.get<CapacitySnapshot>(`/api/capacity-plans/${p}/snapshot`)});}
 save(d:CapacityDraft):Observable<CapacityPlan>{const body={name:d.name.trim(),description:d.description.trim()||null,periodStart:d.periodStart,periodEnd:d.periodEnd,portfolioId:d.portfolioId||null,projectIds:[...new Set(d.projectIds)],members:d.members.map(x=>({...x,teamId:x.teamId||null})),allocations:d.allocations.map(x=>({...x,id:x.id||null})),viewerUserIds:[...new Set(d.viewerUserIds)]};return d.id?this.api.put(`/api/capacity-plans/${encodeURIComponent(d.id)}`,body,{ifMatch:d.version}):this.api.post('/api/capacity-plans',body,{idempotencyKey:this.api.newIdempotencyKey()});}
 share(p:CapacityPlan,viewerUserIds:readonly string[]):Observable<CapacityPlan>{return this.api.put(`/api/capacity-plans/${encodeURIComponent(p.id)}/sharing`,{viewerUserIds},{ifMatch:p.version});}
 archive(p:CapacityPlan){return this.api.delete(`/api/capacity-plans/${encodeURIComponent(p.id)}`,{ifMatch:p.version});}
 scenario(p:CapacityPlan,allocations:CapacityDraft['allocations']):Observable<CapacityScenario>{return this.api.post(`/api/capacity-plans/${encodeURIComponent(p.id)}/scenarios`,{allocations:allocations.map(x=>({...x,id:x.id||null}))},{ifMatch:p.version});}
}
