import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ActivatedRoute,Router,RouterLink} from '@angular/router';
import {IonBackButton,IonButtons,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonTitle,IonToolbar} from '@ionic/angular/standalone';
import {finalize} from 'rxjs';
import {normalizeApiError,ZumboSessionService} from '@zumbo/modern-shared';
import {MobileConnectivityService} from '../../shell/mobile-connectivity.service';
import {canManageMobileTeam,isMobileTeamOwner,mobileTeamAuditLabel,mobileTeamRoleLabel,mobileTeamStatusLabel,systemPermission} from './mobile-team.core';
import {MobileTeam,MobileTeamAudit,MobileTeamContext,MobileTeamMember} from './mobile-team.models';
import {MobileTeamService} from './mobile-team.service';
@Component({selector:'zumbo-mobile-teams',imports:[FormsModule,RouterLink,IonBackButton,IonButtons,IonContent,IonHeader,IonRefresher,IonRefresherContent,IonTitle,IonToolbar],providers:[MobileTeamService],templateUrl:'./mobile-team.page.html',styleUrl:'./mobile-team.page.scss'})
export class MobileTeamPage{private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly api=inject(MobileTeamService);protected readonly session=inject(ZumboSessionService);protected readonly connectivity=inject(MobileConnectivityService);protected readonly teamId=this.route.snapshot.paramMap.get('teamId')||'';protected readonly context=signal<MobileTeamContext|null>(null);protected readonly team=signal<MobileTeam|null>(null);protected readonly audit=signal<readonly MobileTeamAudit[]>([]);protected readonly loading=signal(true);protected readonly busy=signal(false);protected readonly error=signal<string|null>(null);protected readonly notice=signal<string|null>(null);protected name='';protected inviteEmail='';protected inviteRole='Member';protected readonly canCreate=computed(()=>{const user=this.session.currentUser(),ctx=this.context();return!!user&&!!ctx&&systemPermission(ctx.roles,user.roles,'TeamManage');});protected readonly canManage=computed(()=>{const user=this.session.currentUser(),team=this.team();return!!user&&!!team&&canManageMobileTeam(team,user.id);});protected readonly canArchive=computed(()=>{const user=this.session.currentUser(),team=this.team();return!!user&&!!team&&isMobileTeamOwner(team,user.id);});
 constructor(){this.load();}
 protected load(done?:()=>void){const user=this.session.currentUser();if(!user){this.loading.set(false);this.error.set('Oturum bulunamadı.');done?.();return;}this.loading.set(true);this.error.set(null);this.api.load(user.organizationId).pipe(finalize(()=>{this.loading.set(false);done?.();})).subscribe({next:value=>{this.context.set(value);const selected=this.teamId?value.teams.find(item=>item.id===this.teamId&&!item.archived)||null:null;this.team.set(selected);this.name=selected?.name||'';if(this.teamId&&!selected)this.error.set('Ekip bulunamadı veya erişiminiz yok.');if(selected)this.loadAudit(selected,value);},error:()=>this.error.set('Ekipler yüklenemedi.')});}
 protected refresh(event:Event){this.load(()=>void(event.target as unknown as{complete():Promise<void>}).complete());}
 protected create(){const user=this.session.currentUser();if(!user||!this.canCreate()||!this.name.trim())return;this.mutate(this.api.create(user.organizationId,user.id,this.name),value=>void this.router.navigate(['/teams',value.id]));}
 protected save(){const team=this.team();if(!team||!this.canManage()||!this.name.trim())return;this.mutate(this.api.update(team,this.name),value=>{this.team.set(value);this.notice.set('Ekip kaydedildi.');});}
 protected invite(){const team=this.team();if(!team||!this.canManage()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.inviteEmail.trim()))return;this.mutate(this.api.invite(team,this.inviteEmail,this.inviteRole),value=>{this.team.set(value);this.inviteEmail='';this.notice.set('Ekip daveti gönderildi.');});}
 protected remove(member:MobileTeamMember){const team=this.team();if(!team||!this.canManage()||member.role==='Owner'||!confirm(`${member.email} ekipten kaldırılsın mı?`))return;this.mutate(this.api.remove(team,member.userId||member.email),value=>this.team.set(value));}
 protected archive(){const team=this.team();if(!team||!this.canArchive()||!confirm('Bu ekip arşivlensin mi?'))return;this.mutate(this.api.archive(team),()=>void this.router.navigate(['/workspace/teams']));}
 protected roleLabel(value:string){return mobileTeamRoleLabel(value);}protected statusLabel(value:string){return mobileTeamStatusLabel(value);}protected activityLabel(value:string){return mobileTeamAuditLabel(value);}protected date(value:string){return new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value));}
 private loadAudit(team:MobileTeam,context:MobileTeamContext){const user=this.session.currentUser();const allowed=!!user&&systemPermission(context.roles,user.roles,'AuditRead');this.api.audit(team.id,allowed).subscribe(value=>this.audit.set(value.slice(0,8)));}
 private mutate<T>(request:import('rxjs').Observable<T>,done:(value:T)=>void){if(this.busy()||this.connectivity.offline())return;this.busy.set(true);this.error.set(null);this.notice.set(null);request.pipe(finalize(()=>this.busy.set(false))).subscribe({next:done,error:value=>this.error.set(normalizeApiError(value).message||'İşlem tamamlanamadı.')});}
}
