import { AutomationActionDraft, AutomationConditionDraft, AutomationRole, AutomationRule, AutomationRuleDraft, AutomationRuleSummary, WorkRecurrence, WorkRecurrenceDraft, WorkTemplate, WorkTemplateDraft } from './automation.models';

export const automationLimits = Object.freeze({ ruleConditions: 20, ruleActions: 10, ruleHourlyLimit: 1000, ruleChainDepth: 10, labelCount: 50, labelLength: 50 });
export const automationEventTypes = Object.freeze([{ value: 'WorkItemCreated', label: 'İş oluşturulduğunda' }, { value: 'WorkItemUpdated', label: 'İş güncellendiğinde' }, { value: 'WorkItemTransitioned', label: 'İş durum değiştirdiğinde' }]);
export const automationConditionFields = Object.freeze(['Status', 'PreviousStatus', 'Priority', 'Type', 'AssigneeUserId', 'Labels']);
export const automationConditionOperators = Object.freeze(['Equals', 'NotEquals', 'Contains', 'NotContains', 'IsEmpty', 'IsNotEmpty']);
export const automationActionTypes = Object.freeze(['AssignToActor', 'AssignUser', 'ClearAssignee', 'AddLabel', 'RemoveLabel', 'SetPriority', 'AddComment']);

export function hasAutomationPermission(roleName: string | null, roles: readonly AutomationRole[], permission: string): boolean {
  const role = roles.find(candidate => candidate.name === roleName && candidate.isActive);
  return !!role?.permissions.some(candidate => candidate === '*' || candidate === permission);
}

export function newRuleDraft(): AutomationRuleDraft { return { name: '', description: '', triggerType: 'Event', eventType: 'WorkItemCreated', intervalMinutes: 60, startAtLocal: '', conditionMode: 'All', conditions: [], actions: [{ type: 'AddLabel', value: '' }], maximumExecutionsPerHour: 100, maximumChainDepth: 3 }; }
export function ruleDraft(rule: AutomationRule): AutomationRuleDraft { const definition = rule.definition; const condition = definition?.condition; const conditions = !condition ? [] : condition.kind === 'Field' ? [condition] : condition.children; return { id: rule.id, name: definition?.name ?? '', description: definition?.description ?? '', triggerType: definition?.trigger.type ?? 'Event', eventType: definition?.trigger.eventType ?? 'WorkItemCreated', intervalMinutes: definition?.trigger.intervalMinutes ?? 60, startAtLocal: toLocalInput(definition?.trigger.startAtUtc), conditionMode: condition?.kind === 'Any' ? 'Any' : 'All', conditions: conditions.map(item => ({ field: item.field ?? 'Status', operator: item.operator ?? 'Equals', value: item.value ?? '' })), actions: (definition?.actions ?? []).map(item => ({ type: item.type, value: item.value ?? '' })), maximumExecutionsPerHour: definition?.maximumExecutionsPerHour ?? 100, maximumChainDepth: definition?.maximumChainDepth ?? 3 }; }
export function ruleRequest(projectId: string, draft: AutomationRuleDraft): unknown { const conditions = draft.conditions.map(item => ({ kind: 'Field', field: item.field, operator: item.operator, value: conditionNeedsValue(item.operator) ? item.value.trim() : null, children: [] })); return { projectId, name: draft.name.trim(), description: draft.description.trim() || null, trigger: draft.triggerType === 'Schedule' ? { type: 'Schedule', eventType: null, intervalMinutes: Number(draft.intervalMinutes), startAtUtc: toUtc(draft.startAtLocal) } : { type: 'Event', eventType: draft.eventType, intervalMinutes: null, startAtUtc: null }, condition: conditions.length === 0 ? null : conditions.length === 1 ? conditions[0] : { kind: draft.conditionMode, field: null, operator: null, value: null, children: conditions }, actions: draft.actions.map(item => ({ type: item.type, value: actionNeedsValue(item.type) ? item.value.trim() : null })), maximumExecutionsPerHour: Number(draft.maximumExecutionsPerHour), maximumChainDepth: Number(draft.maximumChainDepth) }; }
export function validRule(draft: AutomationRuleDraft): boolean { return !!draft.name.trim() && draft.actions.length > 0 && draft.actions.length <= automationLimits.ruleActions && draft.conditions.length <= automationLimits.ruleConditions && (draft.triggerType !== 'Schedule' || draft.intervalMinutes >= 5) && draft.maximumExecutionsPerHour >= 1 && draft.maximumExecutionsPerHour <= automationLimits.ruleHourlyLimit && draft.maximumChainDepth >= 1 && draft.maximumChainDepth <= automationLimits.ruleChainDepth && draft.conditions.every(item => !conditionNeedsValue(item.operator) || !!item.value.trim()) && draft.actions.every(item => !actionNeedsValue(item.type) || !!item.value.trim()); }
export function actionNeedsValue(type: string): boolean { return ['AssignUser', 'AddLabel', 'RemoveLabel', 'SetPriority', 'AddComment'].includes(type); }
export function conditionNeedsValue(type: string): boolean { return !['IsEmpty', 'IsNotEmpty'].includes(type); }
export function conditionFieldLabel(value: string): string { return ({ Status: 'Durum', PreviousStatus: 'Önceki durum', Priority: 'Öncelik', Type: 'İş türü', AssigneeUserId: 'Atanan kullanıcı', Labels: 'Etiketler' } as Record<string, string>)[value] ?? value; }
export function conditionOperatorLabel(value: string): string { return ({ Equals: 'Eşittir', NotEquals: 'Eşit değildir', Contains: 'İçerir', NotContains: 'İçermez', IsEmpty: 'Boş', IsNotEmpty: 'Boş değil' } as Record<string, string>)[value] ?? value; }
export function actionTypeLabel(value: string): string { return ({ AssignToActor: 'Tetikleyen kullanıcıya ata', AssignUser: 'Kullanıcıya ata', ClearAssignee: 'Atamayı kaldır', AddLabel: 'Etiket ekle', RemoveLabel: 'Etiketi kaldır', SetPriority: 'Öncelik ayarla', AddComment: 'Yorum ekle' } as Record<string, string>)[value] ?? value; }
export function ruleState(rule: AutomationRuleSummary): string { return rule.archived ? 'Arşiv' : !rule.publishedVersion ? 'Taslak' : rule.active ? 'Etkin' : 'Duraklatıldı'; }
export function triggerLabel(rule: AutomationRuleSummary): string { return rule.triggerType === 'Schedule' ? 'Zamanlanmış' : automationEventTypes.find(item => item.value === rule.eventType)?.label ?? 'Olay'; }
export function runState(value: string): string { return ({ Succeeded: 'Başarılı', Skipped: 'Atlandı', Running: 'Çalışıyor', Pending: 'Sırada', RetryScheduled: 'Yeniden denenecek', DeadLetter: 'Müdahale gerekli' } as Record<string, string>)[value] ?? 'Bilinmiyor'; }

export function newTemplateDraft(boardId: string, type: string): WorkTemplateDraft { return { boardId, name: '', title: '', description: '', type, priority: 'Medium', assigneeUserId: '', dueAfterDays: null, labelsText: '', customFields: [] }; }
export function templateDraft(value: WorkTemplate): WorkTemplateDraft { return { id: value.id, version: value.version, boardId: value.boardId, name: value.name, title: value.title, description: value.description, type: value.type, priority: value.priority, assigneeUserId: value.assigneeUserId ?? '', dueAfterDays: value.dueAfterDays ?? null, labelsText: value.labels.join(', '), customFields: value.customFields }; }
export function templateRequest(projectId: string, draft: WorkTemplateDraft): unknown { return { ...(draft.id ? {} : { projectId }), boardId: draft.boardId, name: draft.name.trim(), title: draft.title.trim(), description: draft.description.trim() || null, type: draft.type, priority: draft.priority, assigneeUserId: draft.assigneeUserId || null, teamId: null, dueAfterDays: draft.dueAfterDays, labels: normalizeLabels(draft.labelsText), customFields: draft.customFields }; }
export function normalizeLabels(value: string): readonly string[] { const seen = new Set<string>(); return value.split(/[\n,]+/).map(item => item.trim()).filter(item => { const key = item.toLowerCase(); if (!item || seen.has(key)) return false; seen.add(key); return true; }).slice(0, automationLimits.labelCount); }
export function newRecurrenceDraft(templateId = ''): WorkRecurrenceDraft { const date = new Date(Date.now() + 15 * 60_000); date.setSeconds(0, 0); return { templateId, frequency: 'Weekly', interval: 1, startAtLocal: toLocalInput(date.toISOString()), endAtLocal: '', maxOccurrences: 12 }; }
export function recurrenceRequest(projectId: string, draft: WorkRecurrenceDraft): unknown { return { projectId, templateId: draft.templateId, frequency: draft.frequency, interval: Number(draft.interval), startAtUtc: toUtc(draft.startAtLocal), endAtUtc: toUtc(draft.endAtLocal), maxOccurrences: Number(draft.maxOccurrences) }; }
export function recurrenceState(value: WorkRecurrence): string { return value.archived ? 'Arşiv' : !value.nextRunAtUtc || value.scheduledOccurrences >= value.maxOccurrences ? 'Tamamlandı' : value.active ? 'Etkin' : 'Duraklatıldı'; }
export function frequencyLabel(value: WorkRecurrence): string { const unit = ({ Daily: 'gün', Weekly: 'hafta', Monthly: 'ay' } as Record<string, string>)[value.frequency] ?? 'dönem'; return value.interval === 1 ? `Her ${unit}` : `Her ${value.interval} ${unit}`; }
export function automationError(error: { readonly code?: string; readonly message?: string } | null | undefined, fallback: string): string { return error?.message ?? fallback; }
function toUtc(value?: string | null): string | null { if (!value) return null; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString(); }
function toLocalInput(value?: string | null): string { if (!value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
